@extends('layouts.app')

@section('title', 'Anular ajuste de proveedor')
@section('section', 'Proveedores y cargas')

@section('content')
    @php($money = fn (float|int|string|null $value): string => 'S/ '.number_format((float) ($value ?? 0), 2, ',', '.'))
    <header class="reveal-up border-b border-line pb-7"><a href="{{ route('cargas-proveedor.show', $load) }}" class="font-mono text-[9px] font-semibold tracking-[0.18em] text-signal uppercase">← Volver a la carga</a><p class="mt-5 font-mono text-[10px] font-semibold tracking-[0.24em] text-danger uppercase">Auditoría / {{ $adjustment->numero_ajuste }}</p><h1 class="mt-3 font-display text-4xl font-extrabold text-ink-950 uppercase">Anular ajuste</h1><p class="mt-3 text-sm text-steel-500">La cuenta por pagar aumentará nuevamente en {{ $money($adjustment->monto) }}. Si fue una devolución, la mercadería regresará al inventario.</p></header>
    <form method="POST" action="{{ route('cargas-proveedor.ajustes.anulacion.store', [$load, $adjustment]) }}" class="mt-6 max-w-3xl border border-line bg-paper shadow-panel">@csrf<div class="grid gap-5 p-5 sm:p-6"><div class="grid gap-4 sm:grid-cols-3"><div class="border border-line bg-canvas p-4"><p class="font-mono text-[8px] text-steel-500 uppercase">Tipo</p><p class="mt-2 font-display text-xl font-bold uppercase">{{ $adjustment->tipo }}</p></div><div class="border border-line bg-canvas p-4"><p class="font-mono text-[8px] text-steel-500 uppercase">Importe</p><p class="mt-2 font-display text-xl font-bold">{{ $money($adjustment->monto) }}</p></div><div class="border border-line bg-canvas p-4"><p class="font-mono text-[8px] text-steel-500 uppercase">Carga</p><p class="mt-2 font-mono text-sm font-bold">{{ $load->numero_carga }}</p></div></div><x-form-field name="motivo_anulacion" label="Motivo de anulación" hint="Mínimo 10 caracteres" required><textarea id="motivo_anulacion" name="motivo_anulacion" rows="5" minlength="10" maxlength="255" class="w-full border border-line bg-white px-4 py-3 text-sm outline-none focus:border-danger" required autofocus>{{ old('motivo_anulacion') }}</textarea></x-form-field></div><div class="flex flex-col-reverse gap-3 border-t border-line p-5 sm:flex-row sm:justify-end"><a href="{{ route('cargas-proveedor.show', $load) }}" class="inline-flex min-h-12 items-center justify-center border border-line px-6 font-display text-sm font-bold uppercase">Conservar ajuste</a><button type="submit" class="inline-flex min-h-12 items-center justify-center bg-danger px-7 font-display text-sm font-bold text-white uppercase">Confirmar anulación</button></div></form>
@endsection
