@props([
    'detailIndex',
    'index',
    'weighing' => [],
    'crateTypes',
    'showErrors' => true,
])

@php
    $crateCount = (int) ($weighing['cantidad_jabas'] ?? 0);
    $fieldError = fn (string $field): ?string => $showErrors ? $errors->first("detalles.$detailIndex.pesajes.$index.$field") : null;
    $fieldId = fn (string $field): string => "detalles-$detailIndex-pesajes-$index-$field";
@endphp

<article data-sale-weighing class="border border-line bg-paper shadow-sm">
    <header class="flex items-center justify-between gap-4 border-b border-line bg-canvas px-4 py-3">
        <div class="flex items-center gap-3"><span data-sale-weighing-number class="grid size-7 place-items-center bg-ink-950 font-mono text-[9px] font-bold text-hazard">{{ is_numeric($index) ? (int) $index + 1 : 1 }}</span><div><p class="font-display text-base font-bold text-ink-950 uppercase">Pesaje de salida</p><p data-sale-weighing-description class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Peso bruto menos tara</p></div></div>
        <button type="button" data-remove-sale-weighing class="inline-flex min-h-9 items-center border border-line px-3 font-mono text-[8px] font-semibold tracking-wider text-steel-500 uppercase transition hover:border-danger hover:bg-danger-soft hover:text-danger disabled:opacity-30">Eliminar</button>
    </header>

    <div data-sale-weighing-fields class="grid gap-4 p-4 sm:grid-cols-2 xl:grid-cols-5">
        <div data-sale-live-field><label for="{{ $fieldId('cantidad-jabas') }}" class="font-mono text-[8px] font-semibold tracking-wider text-ink-700 uppercase">Jabas</label><input data-sale-crates id="{{ $fieldId('cantidad-jabas') }}" name="detalles[{{ $detailIndex }}][pesajes][{{ $index }}][cantidad_jabas]" value="{{ $weighing['cantidad_jabas'] ?? 0 }}" type="number" min="0" max="99999" step="1" class="mt-2 min-h-11 w-full border border-line bg-white px-3 text-sm font-semibold text-ink-950 outline-none focus:border-signal" required>@if ($fieldError('cantidad_jabas'))<p class="mt-2 text-xs font-medium text-danger">{{ $fieldError('cantidad_jabas') }}</p>@endif</div>
        <div data-sale-live-field><label for="{{ $fieldId('tipo-jaba') }}" class="font-mono text-[8px] font-semibold tracking-wider text-ink-700 uppercase">Tipo de jaba</label><select data-sale-crate-type id="{{ $fieldId('tipo-jaba') }}" name="detalles[{{ $detailIndex }}][pesajes][{{ $index }}][tipo_jaba_id]" class="mt-2 min-h-11 w-full border border-line bg-white px-3 text-sm font-semibold text-ink-950 outline-none focus:border-signal" @disabled($crateCount === 0)><option value="">Sin jabas</option>@foreach ($crateTypes as $crateType)<option value="{{ $crateType->id }}" data-tare="{{ $crateType->tara_referencial_kg }}" @selected((string) ($weighing['tipo_jaba_id'] ?? '') === (string) $crateType->id)>{{ $crateType->nombre }} · {{ number_format((float) $crateType->tara_referencial_kg, 3, ',', '.') }} kg</option>@endforeach</select>@if ($fieldError('tipo_jaba_id'))<p class="mt-2 text-xs font-medium text-danger">{{ $fieldError('tipo_jaba_id') }}</p>@endif</div>
        <div data-sale-live-field><label for="{{ $fieldId('tara') }}" class="font-mono text-[8px] font-semibold tracking-wider text-ink-700 uppercase">Tara kg/u</label><input data-sale-tare id="{{ $fieldId('tara') }}" name="detalles[{{ $detailIndex }}][pesajes][{{ $index }}][tara_unitaria_aplicada_kg]" value="{{ $weighing['tara_unitaria_aplicada_kg'] ?? '0.000' }}" type="number" min="0" max="9999999.999" step="0.001" class="mt-2 min-h-11 w-full border border-line bg-white px-3 text-sm font-semibold text-ink-950 outline-none focus:border-signal disabled:bg-steel-300/20 disabled:text-steel-500" @disabled($crateCount === 0)>@if ($fieldError('tara_unitaria_aplicada_kg'))<p class="mt-2 text-xs font-medium text-danger">{{ $fieldError('tara_unitaria_aplicada_kg') }}</p>@endif</div>
        <div data-sale-live-field><label for="{{ $fieldId('cantidad-pollos') }}" class="font-mono text-[8px] font-semibold tracking-wider text-ink-700 uppercase">Pollos</label><input data-sale-birds id="{{ $fieldId('cantidad-pollos') }}" name="detalles[{{ $detailIndex }}][pesajes][{{ $index }}][cantidad_pollos]" value="{{ $weighing['cantidad_pollos'] ?? '' }}" type="number" min="1" max="9999999" step="1" placeholder="0" class="mt-2 min-h-11 w-full border border-line bg-white px-3 text-sm font-semibold text-ink-950 outline-none placeholder:text-steel-300 focus:border-signal" required>@if ($fieldError('cantidad_pollos'))<p class="mt-2 text-xs font-medium text-danger">{{ $fieldError('cantidad_pollos') }}</p>@endif</div>
        <div><label data-sale-weight-label for="{{ $fieldId('peso-bruto') }}" class="font-mono text-[8px] font-semibold tracking-wider text-ink-700 uppercase">Peso bruto kg</label><input data-sale-gross-weight id="{{ $fieldId('peso-bruto') }}" name="detalles[{{ $detailIndex }}][pesajes][{{ $index }}][peso_bruto_kg]" value="{{ $weighing['peso_bruto_kg'] ?? '' }}" type="number" min="0.001" max="999999999.999" step="0.001" placeholder="0.000" class="mt-2 min-h-11 w-full border border-line bg-white px-3 text-sm font-semibold text-ink-950 outline-none placeholder:text-steel-300 focus:border-signal" required>@if ($fieldError('peso_bruto_kg'))<p class="mt-2 text-xs font-medium text-danger">{{ $fieldError('peso_bruto_kg') }}</p>@endif</div>
        <div data-sale-observation-field class="sm:col-span-2 xl:col-span-4"><label for="{{ $fieldId('observacion') }}" class="font-mono text-[8px] font-semibold tracking-wider text-ink-700 uppercase">Observación <span class="font-sans font-normal tracking-normal text-steel-500 normal-case">(opcional)</span></label><input id="{{ $fieldId('observacion') }}" name="detalles[{{ $detailIndex }}][pesajes][{{ $index }}][observacion]" value="{{ $weighing['observacion'] ?? '' }}" type="text" maxlength="255" placeholder="Referencia o incidencia del pesaje..." class="mt-2 min-h-11 w-full border border-line bg-white px-3 text-sm text-ink-950 outline-none placeholder:text-steel-300 focus:border-signal">@if ($fieldError('observacion'))<p class="mt-2 text-xs font-medium text-danger">{{ $fieldError('observacion') }}</p>@endif</div>
        <div class="border-l-4 border-signal bg-signal-soft p-3"><p class="font-mono text-[8px] tracking-wider text-signal uppercase">Peso neto</p><p data-sale-net-weight class="mt-1 font-display text-xl font-extrabold text-ink-950">0,000 kg</p></div>
    </div>
</article>
