@extends('layouts.app')

@section('title', 'Nueva conciliación de mercadería')
@section('section', 'Conciliaciones')

@section('content')
    @php
        $quantity = fn (float|int|string|null $value, int $decimals = 0): string => number_format((float) ($value ?? 0), $decimals, ',', '.');
        $selectedProductId = old('producto_id', $preselectedProductId);
        $selectedProduct = $products->firstWhere('id', (int) $selectedProductId);
        $selectedType = old('tipo_conciliacion', 'CIERRE');
    @endphp

    <header class="reveal-up border-b border-line pb-7"><a href="{{ route('conciliaciones-mercaderia.index') }}" class="font-mono text-[9px] font-semibold tracking-[0.18em] text-signal uppercase transition hover:text-ink-950">← Volver a conciliaciones</a><p class="mt-5 font-mono text-[10px] font-semibold tracking-[0.24em] text-signal uppercase">Inventario / Conteo físico</p><h1 class="mt-3 font-display text-4xl leading-none font-extrabold tracking-tight text-ink-950 uppercase sm:text-5xl">Nueva conciliación</h1><p class="mt-3 max-w-3xl text-sm leading-6 text-steel-500">Ingresa lo encontrado físicamente. El sistema comparará ambos saldos y generará las correcciones necesarias de forma automática.</p></header>

    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_400px]">
        <form method="POST" action="{{ route('conciliaciones-mercaderia.store') }}" data-reconciliation-form class="reveal-up reveal-up-delay-1 border border-line bg-paper shadow-panel" novalidate>
            @csrf
            <div class="border-b border-line px-5 py-5 sm:px-6"><p class="font-mono text-[9px] font-semibold tracking-[0.18em] text-signal uppercase">Conteo / Datos</p><h2 class="mt-1 font-display text-2xl font-bold text-ink-950 uppercase">Existencia encontrada</h2></div>
            <div class="grid gap-6 p-5 sm:p-6">
                <x-form-field name="producto_id" label="Producto" hint="Se tomará el saldo actual al confirmar" required><select id="producto_id" name="producto_id" data-reconciliation-product class="min-h-12 w-full border border-line bg-white px-4 text-sm font-semibold text-ink-950 outline-none transition focus:border-signal focus:ring-2 focus:ring-signal/15" required autofocus><option value="">Selecciona un producto</option>@foreach ($products as $product)<option value="{{ $product->id }}" data-birds="{{ $product->pollos_disponibles }}" data-kilograms="{{ $product->kg_disponibles }}" @selected((string) $selectedProductId === (string) $product->id)>{{ $product->nombre }} · sistema {{ $quantity($product->pollos_disponibles) }} aves · {{ $quantity($product->kg_disponibles, 3) }} kg</option>@endforeach</select></x-form-field>

                <fieldset><legend class="font-mono text-[10px] font-semibold tracking-[0.16em] text-ink-700 uppercase">Tipo de conciliación <span class="text-danger" aria-hidden="true">*</span></legend><div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="relative cursor-pointer border border-line bg-white p-4 transition has-[:checked]:border-signal has-[:checked]:bg-signal-soft/60 has-[:focus-visible]:ring-2 has-[:focus-visible]:ring-signal/30"><input type="radio" name="tipo_conciliacion" value="CIERRE" data-reconciliation-type class="peer sr-only" @checked($selectedType === 'CIERRE')><span class="block font-display text-lg font-bold text-ink-950 uppercase">Cierre</span><span class="mt-1 block text-xs leading-5 text-steel-500">Control periódico al finalizar la operación.</span><span class="absolute top-4 right-4 size-3 border border-steel-300 bg-white peer-checked:border-signal peer-checked:bg-signal"></span></label><label class="relative cursor-pointer border border-line bg-white p-4 transition has-[:checked]:border-hazard has-[:checked]:bg-hazard-soft/50 has-[:focus-visible]:ring-2 has-[:focus-visible]:ring-hazard/40"><input type="radio" name="tipo_conciliacion" value="EXTRAORDINARIA" data-reconciliation-type class="peer sr-only" @checked($selectedType === 'EXTRAORDINARIA')><span class="block font-display text-lg font-bold text-ink-950 uppercase">Extraordinaria</span><span class="mt-1 block text-xs leading-5 text-steel-500">Reconteo por una incidencia o revisión puntual.</span><span class="absolute top-4 right-4 size-3 border border-steel-300 bg-white peer-checked:border-hazard peer-checked:bg-hazard"></span></label></div>@error('tipo_conciliacion')<p class="mt-2 text-sm font-medium text-danger">{{ $message }}</p>@enderror</fieldset>

                <div class="grid gap-5 sm:grid-cols-2"><x-form-field name="cantidad_pollos_fisico" label="Aves encontradas" hint="Conteo físico total" required><div class="flex min-h-12 border border-line bg-white transition focus-within:border-signal focus-within:ring-2 focus-within:ring-signal/15"><input id="cantidad_pollos_fisico" name="cantidad_pollos_fisico" data-reconciliation-physical-birds value="{{ old('cantidad_pollos_fisico', $selectedProduct?->pollos_disponibles ?? 0) }}" type="number" min="0" max="2000000000" step="1" inputmode="numeric" class="min-w-0 flex-1 px-4 text-sm font-semibold text-ink-950 outline-none" required><span class="grid w-16 shrink-0 place-items-center border-l border-line bg-canvas font-mono text-[9px] text-steel-500 uppercase">Aves</span></div></x-form-field><x-form-field name="peso_fisico_kg" label="Peso encontrado" hint="Máximo 3 decimales" required><div class="flex min-h-12 border border-line bg-white transition focus-within:border-signal focus-within:ring-2 focus-within:ring-signal/15"><input id="peso_fisico_kg" name="peso_fisico_kg" data-reconciliation-physical-kilograms value="{{ old('peso_fisico_kg', $selectedProduct?->kg_disponibles ?? '0.000') }}" type="number" min="0" max="999999999.999" step="0.001" inputmode="decimal" class="min-w-0 flex-1 px-4 text-sm font-semibold text-ink-950 outline-none" required><span class="grid w-16 shrink-0 place-items-center border-l border-line bg-canvas font-mono text-[9px] text-steel-500 uppercase">kg</span></div></x-form-field></div>

                <div data-reconciliation-observation-panel><x-form-field name="observacion" label="Observación" hint="Obligatoria para conciliaciones extraordinarias"><textarea id="observacion" name="observacion" data-reconciliation-observation rows="4" minlength="10" maxlength="255" placeholder="Describe el cierre o la incidencia que motivó el conteo..." class="w-full resize-y border border-line bg-white px-4 py-3 text-sm text-ink-950 outline-none transition placeholder:text-steel-300 focus:border-signal focus:ring-2 focus:ring-signal/15">{{ old('observacion') }}</textarea></x-form-field></div>

                <div class="border-l-4 border-hazard bg-hazard-soft px-4 py-3 text-sm leading-6 text-ink-700" role="status"><strong>Importante:</strong> realiza el conteo sin registrar cargas, ventas ni ajustes simultáneos sobre este producto.</div>
            </div>
            <div class="flex flex-col-reverse gap-3 border-t border-line px-5 py-5 sm:flex-row sm:justify-end sm:px-6"><a href="{{ route('conciliaciones-mercaderia.index') }}" class="inline-flex min-h-12 items-center justify-center border border-line px-6 font-display text-sm font-bold tracking-wider text-ink-700 uppercase transition hover:border-ink-950 hover:text-ink-950">Cancelar</a><button type="submit" @disabled($products->isEmpty()) class="inline-flex min-h-12 items-center justify-center bg-ink-950 px-7 font-display text-sm font-bold tracking-wider text-white uppercase transition hover:bg-ink-800 disabled:cursor-not-allowed disabled:bg-steel-300">Confirmar conciliación</button></div>
        </form>

        <aside class="grid content-start gap-6"><section data-reconciliation-preview-panel class="industrial-hatch panel-cut reveal-up reveal-up-delay-2 bg-ink-950 p-6 text-white shadow-panel" aria-labelledby="reconciliation-preview-title"><p class="font-mono text-[9px] tracking-[0.2em] text-hazard uppercase">Vista previa / Diferencia</p><h2 id="reconciliation-preview-title" class="mt-2 font-display text-2xl font-bold uppercase">Resultado del conteo</h2><p data-reconciliation-product-name class="mt-3 text-sm text-steel-300">Selecciona el producto conciliado.</p><div class="mt-6 grid grid-cols-2 gap-px border border-white/10 bg-white/10"><div class="bg-ink-950 p-4"><p class="font-mono text-[8px] text-steel-300 uppercase">Sistema</p><p data-reconciliation-system-birds class="mt-2 font-display text-2xl font-bold">{{ $quantity($selectedProduct?->pollos_disponibles) }}</p><p data-reconciliation-system-kilograms class="mt-1 text-xs text-steel-300">{{ $quantity($selectedProduct?->kg_disponibles, 3) }} kg</p></div><div class="bg-ink-950 p-4"><p class="font-mono text-[8px] text-steel-300 uppercase">Conteo físico</p><p data-reconciliation-preview-physical-birds class="mt-2 font-display text-2xl font-bold text-hazard">{{ $quantity(old('cantidad_pollos_fisico', $selectedProduct?->pollos_disponibles)) }}</p><p data-reconciliation-preview-physical-kilograms class="mt-1 text-xs text-steel-300">{{ $quantity(old('peso_fisico_kg', $selectedProduct?->kg_disponibles), 3) }} kg</p></div></div><div class="mt-px border border-white/10 bg-white/5 p-4"><p class="font-mono text-[8px] tracking-wider text-steel-300 uppercase">Diferencia que se ajustará</p><div class="mt-3 grid grid-cols-2 gap-4"><p data-reconciliation-difference-birds class="font-display text-2xl font-bold text-signal">0 aves</p><p data-reconciliation-difference-kilograms class="font-display text-2xl font-bold text-signal">0,000 kg</p></div><p data-reconciliation-message class="mt-3 text-xs leading-5 text-steel-300" aria-live="polite">Un saldo sin diferencia no generará ajustes.</p></div></section><section class="reveal-up reveal-up-delay-2 border border-line bg-paper p-5 shadow-panel"><p class="font-mono text-[9px] font-semibold tracking-wider text-signal uppercase">Ajuste automático</p><p class="mt-2 text-sm leading-6 text-steel-500">Las diferencias positivas sumarán existencia y las negativas la descontarán. Si aves y peso difieren en sentidos opuestos, se crearán dos ajustes enlazados.</p></section></aside>
    </div>
@endsection
