@extends('layouts.app')

@section('title', 'Conciliaciones de mercadería')
@section('section', 'Conciliaciones')

@section('content')
    @php($quantity = fn (float|int|string|null $value, int $decimals = 0): string => number_format((float) ($value ?? 0), $decimals, ',', '.'))

    <header class="reveal-up flex flex-col gap-6 border-b border-line pb-7 xl:flex-row xl:items-end xl:justify-between">
        <div class="max-w-3xl"><p class="font-mono text-[10px] font-semibold tracking-[0.24em] text-signal uppercase">Inventario / Control físico</p><h1 class="mt-3 font-display text-4xl leading-none font-extrabold tracking-tight text-ink-950 uppercase sm:text-5xl">Conciliaciones</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-steel-500">Contrasta el conteo físico con el saldo del sistema y conserva cada diferencia junto con sus ajustes automáticos.</p></div>
        <a href="{{ route('conciliaciones-mercaderia.create') }}" class="group inline-flex min-h-12 items-center justify-between gap-5 bg-ink-950 px-5 font-display text-sm font-bold tracking-wider text-white uppercase transition hover:bg-ink-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-hazard">Nueva conciliación<span class="grid size-7 place-items-center bg-hazard text-lg leading-none text-ink-950 transition group-hover:rotate-90" aria-hidden="true">+</span></a>
    </header>

    <section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Resumen de conciliaciones de hoy">
        <x-stat-card label="Conciliaciones hoy" :value="$quantity($todaySummary?->total)" meta="Controles registrados" tone="signal"><x-slot:icon><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="m4 7 8-4 8 4-8 4-8-4Z" /><path d="m4 7v10l8 4 8-4V7" /><path d="m9 15 2 2 4-5" /></svg></x-slot:icon></x-stat-card>
        <x-stat-card label="Saldos cuadrados" :value="$quantity($todaySummary?->cuadradas)" meta="Sin diferencias" tone="signal"><x-slot:icon><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="12" cy="12" r="9" /><path d="m8 12 3 3 5-6" /></svg></x-slot:icon></x-stat-card>
        <x-stat-card label="Con diferencia" :value="$quantity($todaySummary?->con_diferencia)" meta="Generaron corrección" :tone="($todaySummary?->con_diferencia ?? 0) > 0 ? 'danger' : 'default'"><x-slot:icon><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M12 4v11m0 4v1" /><circle cx="12" cy="12" r="9" /></svg></x-slot:icon></x-stat-card>
        <x-stat-card label="Variación observada" :value="$quantity($todaySummary?->diferencia_pollos).' aves'" :meta="$quantity($todaySummary?->diferencia_peso_kg, 3).' kg absolutos'" tone="hazard"><x-slot:icon><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M4 8h16M4 16h16M8 4l-4 4 4 4m8 0 4 4-4 4" /></svg></x-slot:icon></x-stat-card>
    </section>

    <form method="GET" action="{{ route('conciliaciones-mercaderia.index') }}" class="reveal-up reveal-up-delay-1 mt-6 grid gap-3 border border-line bg-paper p-4 shadow-sm xl:grid-cols-[minmax(0,1fr)_190px_190px_auto]">
        <div class="relative"><label for="conciliation-search" class="sr-only">Buscar conciliación</label><svg class="pointer-events-none absolute top-1/2 left-4 size-4 -translate-y-1/2 text-steel-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="11" cy="11" r="7" /><path d="m20 20-4-4" /></svg><input id="conciliation-search" name="buscar" type="search" value="{{ $search }}" placeholder="Número, producto u observación..." class="min-h-12 w-full border border-line bg-white pr-4 pl-11 text-sm text-ink-950 outline-none transition placeholder:text-steel-300 focus:border-ink-950 focus:ring-2 focus:ring-hazard/40"></div>
        <div><label for="conciliation-type" class="sr-only">Tipo</label><select id="conciliation-type" name="tipo" class="min-h-12 w-full border border-line bg-white px-4 text-sm font-semibold text-ink-700 outline-none transition focus:border-ink-950 focus:ring-2 focus:ring-hazard/40"><option value="">Todos los tipos</option><option value="CIERRE" @selected($type === 'CIERRE')>Cierre</option><option value="EXTRAORDINARIA" @selected($type === 'EXTRAORDINARIA')>Extraordinaria</option></select></div>
        <div><label for="conciliation-date" class="sr-only">Fecha</label><input id="conciliation-date" name="fecha" type="date" value="{{ $date }}" max="{{ today()->toDateString() }}" class="min-h-12 w-full border border-line bg-white px-4 text-sm font-semibold text-ink-700 outline-none transition focus:border-ink-950 focus:ring-2 focus:ring-hazard/40"></div>
        <div class="flex gap-2"><button type="submit" class="inline-flex min-h-12 flex-1 items-center justify-center bg-ink-950 px-5 font-display text-sm font-bold tracking-wider text-white uppercase transition hover:bg-ink-800 xl:flex-none">Filtrar</button>@if ($search !== '' || $type !== null || $date !== today()->toDateString())<a href="{{ route('conciliaciones-mercaderia.index') }}" class="inline-flex min-h-12 items-center justify-center border border-line px-4 text-xs font-semibold text-steel-500 uppercase transition hover:border-ink-950 hover:text-ink-950" aria-label="Limpiar filtros">×</a>@endif</div>
    </form>

    <section class="reveal-up reveal-up-delay-2 mt-6 overflow-hidden border border-line bg-paper shadow-panel" aria-labelledby="conciliation-history-title">
        <div class="flex items-center justify-between gap-4 border-b border-line px-5 py-5 sm:px-6"><div><p class="font-mono text-[9px] font-semibold tracking-[0.18em] text-hazard uppercase">Auditoría / Conteos</p><h2 id="conciliation-history-title" class="mt-1 font-display text-2xl font-bold text-ink-950 uppercase">Historial de conciliaciones</h2></div><span class="border border-line px-2.5 py-1 font-mono text-[9px] text-steel-500 uppercase">{{ $conciliations->total() }} registros</span></div>

        @if ($conciliations->isEmpty())
            <x-empty-state title="No hay conciliaciones registradas" description="El primer conteo físico y sus diferencias aparecerán aquí." :action-href="route('conciliaciones-mercaderia.create')" action-label="Registrar conciliación"><x-slot:icon><svg class="size-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="m4 7 8-4 8 4-8 4-8-4Z" /><path d="m4 7v10l8 4 8-4V7" /><path d="m8 15 3 3 5-6" /></svg></x-slot:icon></x-empty-state>
        @else
            <div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[1020px] border-collapse text-left" aria-label="Historial de conciliaciones"><thead class="bg-canvas font-mono text-[9px] tracking-[0.16em] text-steel-500 uppercase"><tr><th class="px-6 py-3 font-semibold" scope="col">Conciliación</th><th class="px-6 py-3 font-semibold" scope="col">Producto</th><th class="px-6 py-3 font-semibold" scope="col">Tipo</th><th class="px-6 py-3 text-right font-semibold" scope="col">Diferencia aves</th><th class="px-6 py-3 text-right font-semibold" scope="col">Diferencia peso</th><th class="px-6 py-3 font-semibold" scope="col">Resultado</th><th class="px-6 py-3 text-right font-semibold" scope="col">Acción</th></tr></thead><tbody class="divide-y divide-line">
                @foreach ($conciliations as $conciliation)
                    @php($isBalanced = $conciliation->estaCuadrada())
                    <tr class="transition hover:bg-hazard-soft/20"><td class="px-6 py-4"><p class="font-mono text-xs font-semibold text-ink-950">{{ $conciliation->numero_conciliacion }}</p><p class="mt-1 text-xs text-steel-500">{{ $conciliation->realizada_at->format('d/m/Y · H:i') }}</p></td><td class="px-6 py-4 font-semibold text-ink-950">{{ $conciliation->producto->nombre }}</td><td class="px-6 py-4"><span class="font-mono text-[9px] font-semibold uppercase">{{ $conciliation->tipo_conciliacion === 'CIERRE' ? 'Cierre' : 'Extraordinaria' }}</span></td><td class="px-6 py-4 text-right font-mono text-xs font-semibold {{ $conciliation->diferenciaPollos() === 0 ? 'text-steel-500' : 'text-danger' }}">{{ $conciliation->diferenciaPollos() > 0 ? '+' : '' }}{{ $quantity($conciliation->diferenciaPollos()) }}</td><td class="px-6 py-4 text-right font-mono text-xs font-semibold {{ $conciliation->diferenciaPesoGramos() === 0 ? 'text-steel-500' : 'text-danger' }}">{{ $conciliation->diferenciaPesoGramos() > 0 ? '+' : '' }}{{ $quantity($conciliation->diferenciaPesoGramos() / 1000, 3) }} kg</td><td class="px-6 py-4"><span class="inline-flex border px-2.5 py-1 font-mono text-[8px] font-semibold tracking-wider uppercase {{ $isBalanced ? 'border-signal/30 bg-signal-soft text-signal' : 'border-danger/30 bg-danger-soft text-danger' }}">{{ $isBalanced ? 'Cuadrado' : $conciliation->ajustes_count.' ajuste(s)' }}</span></td><td class="px-6 py-4 text-right"><a href="{{ route('conciliaciones-mercaderia.show', $conciliation) }}" class="inline-flex min-h-9 items-center border border-line px-3 font-mono text-[9px] font-semibold tracking-wider text-ink-700 uppercase transition hover:border-ink-950 hover:bg-ink-950 hover:text-white">Ver detalle</a></td></tr>
                @endforeach
            </tbody></table></div>
            <div class="divide-y divide-line md:hidden">@foreach ($conciliations as $conciliation)@php($isBalanced = $conciliation->estaCuadrada())<article class="p-5"><div class="flex items-start justify-between gap-4"><div><p class="font-mono text-xs font-semibold text-ink-950">{{ $conciliation->numero_conciliacion }}</p><p class="mt-1 text-xs text-steel-500">{{ $conciliation->realizada_at->format('d/m/Y · H:i') }}</p></div><span class="border px-2 py-1 font-mono text-[8px] font-semibold uppercase {{ $isBalanced ? 'border-signal/30 bg-signal-soft text-signal' : 'border-danger/30 bg-danger-soft text-danger' }}">{{ $isBalanced ? 'Cuadrado' : 'Con diferencia' }}</span></div><p class="mt-4 font-display text-xl font-bold text-ink-950 uppercase">{{ $conciliation->producto->nombre }}</p><div class="mt-4 grid grid-cols-2 gap-px border-y border-line bg-line"><div class="bg-paper py-4 pr-3"><p class="font-mono text-[8px] text-steel-500 uppercase">Diferencia aves</p><p class="mt-1 font-display text-2xl font-extrabold">{{ $conciliation->diferenciaPollos() > 0 ? '+' : '' }}{{ $quantity($conciliation->diferenciaPollos()) }}</p></div><div class="bg-paper py-4 pl-3"><p class="font-mono text-[8px] text-steel-500 uppercase">Diferencia peso</p><p class="mt-1 font-display text-2xl font-extrabold">{{ $conciliation->diferenciaPesoGramos() > 0 ? '+' : '' }}{{ $quantity($conciliation->diferenciaPesoGramos() / 1000, 3) }}</p></div></div><a href="{{ route('conciliaciones-mercaderia.show', $conciliation) }}" class="mt-4 inline-flex min-h-10 w-full items-center justify-center border border-ink-950 font-mono text-[9px] font-semibold tracking-wider text-ink-950 uppercase">Ver detalle</a></article>@endforeach</div>
            <x-catalog-pagination :paginator="$conciliations" />
        @endif
    </section>
@endsection
