@extends('layouts.app')

@section('title', 'Detalle de conciliación')
@section('section', 'Conciliaciones')

@section('content')
    @php
        $quantity = fn (float|int|string|null $value, int $decimals = 0): string => number_format((float) ($value ?? 0), $decimals, ',', '.');
        $birdDifference = $conciliation->diferenciaPollos();
        $weightDifference = $conciliation->diferenciaPesoGramos() / 1000;
        $isBalanced = $conciliation->estaCuadrada();
    @endphp

    <header class="reveal-up flex flex-col gap-6 border-b border-line pb-7 xl:flex-row xl:items-end xl:justify-between"><div class="max-w-3xl"><a href="{{ route('conciliaciones-mercaderia.index') }}" class="font-mono text-[9px] font-semibold tracking-[0.18em] text-signal uppercase transition hover:text-ink-950">← Volver a conciliaciones</a><p class="mt-5 font-mono text-[10px] font-semibold tracking-[0.24em] text-signal uppercase">Inventario / {{ $conciliation->numero_conciliacion }}</p><h1 class="mt-3 font-display text-4xl leading-none font-extrabold tracking-tight text-ink-950 uppercase sm:text-5xl">Detalle de conciliación</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-steel-500">Conteo de {{ $conciliation->producto->nombre }} realizado el {{ $conciliation->realizada_at->format('d/m/Y \a \l\a\s H:i') }}.</p></div><span class="inline-flex min-h-12 items-center justify-center border px-5 font-mono text-[10px] font-semibold tracking-wider uppercase {{ $isBalanced ? 'border-signal/30 bg-signal-soft text-signal' : 'border-danger/30 bg-danger-soft text-danger' }}">{{ $isBalanced ? 'Saldo cuadrado' : 'Diferencia corregida' }}</span></header>

    <section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Resultado de la conciliación"><div class="border-l-4 border-steel-300 bg-paper p-5 shadow-sm"><p class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Saldo del sistema</p><p class="mt-2 font-display text-3xl font-extrabold text-ink-950">{{ $quantity($conciliation->cantidad_pollos_sistema) }} aves</p><p class="mt-1 text-xs text-steel-500">{{ $quantity($conciliation->peso_sistema_kg, 3) }} kg</p></div><div class="border-l-4 border-hazard bg-paper p-5 shadow-sm"><p class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Conteo físico</p><p class="mt-2 font-display text-3xl font-extrabold text-ink-950">{{ $quantity($conciliation->cantidad_pollos_fisico) }} aves</p><p class="mt-1 text-xs text-steel-500">{{ $quantity($conciliation->peso_fisico_kg, 3) }} kg</p></div><div class="border-l-4 {{ $isBalanced ? 'border-signal' : 'border-danger' }} bg-paper p-5 shadow-sm"><p class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Diferencia detectada</p><p class="mt-2 font-display text-3xl font-extrabold {{ $isBalanced ? 'text-signal' : 'text-danger' }}">{{ $birdDifference > 0 ? '+' : '' }}{{ $quantity($birdDifference) }} aves</p><p class="mt-1 text-xs {{ $isBalanced ? 'text-steel-500' : 'text-danger' }}">{{ $weightDifference > 0 ? '+' : '' }}{{ $quantity($weightDifference, 3) }} kg</p></div><div class="industrial-hatch border-l-4 border-hazard bg-ink-950 p-5 text-white shadow-sm"><p class="font-mono text-[8px] tracking-wider text-hazard uppercase">Saldo actual</p><p class="mt-2 font-display text-3xl font-extrabold">{{ $quantity($currentBalance->pollos_disponibles) }} aves</p><p class="mt-1 text-xs text-steel-300">{{ $quantity($currentBalance->kg_disponibles, 3) }} kg disponibles</p></div></section>

    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_380px]">
        <div class="grid content-start gap-6"><section class="reveal-up reveal-up-delay-1 overflow-hidden border border-line bg-paper shadow-panel" aria-labelledby="generated-adjustments-title"><div class="flex items-center justify-between gap-4 border-b border-line px-5 py-5 sm:px-6"><div><p class="font-mono text-[9px] font-semibold tracking-[0.18em] text-signal uppercase">Corrección / Enlace</p><h2 id="generated-adjustments-title" class="mt-1 font-display text-2xl font-bold text-ink-950 uppercase">Ajustes generados</h2></div><span class="border border-line px-2.5 py-1 font-mono text-[9px] text-steel-500 uppercase">{{ $conciliation->ajustes->count() }} movimientos</span></div>@if ($conciliation->ajustes->isEmpty())<div class="p-6 sm:p-8"><div class="border-l-4 border-signal bg-signal-soft p-5"><p class="font-display text-xl font-bold text-ink-950 uppercase">Sin correcciones</p><p class="mt-2 text-sm leading-6 text-ink-700">El conteo físico coincidió con el sistema, por lo que no fue necesario modificar la existencia.</p></div></div>@else<div class="divide-y divide-line">@foreach ($conciliation->ajustes as $adjustment)@php($isEntry = $adjustment->tipoAjuste->naturaleza === 'ENTRADA')<article class="p-5 sm:p-6"><div class="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-mono text-[10px] font-semibold text-steel-500">{{ $adjustment->numero_ajuste }}</p><h3 class="mt-1 font-display text-xl font-bold text-ink-950 uppercase">{{ $adjustment->tipoAjuste->nombre }}</h3><p class="mt-2 text-sm text-steel-500">{{ $adjustment->motivo }}</p></div><div class="grid grid-cols-2 gap-3 sm:min-w-64"><div class="border border-line bg-canvas p-3 text-right"><p class="font-mono text-[8px] text-steel-500 uppercase">Aves</p><p class="mt-1 font-display text-xl font-bold {{ $isEntry ? 'text-signal' : 'text-danger' }}">{{ $isEntry ? '+' : '−' }}{{ $quantity($adjustment->cantidad_pollos) }}</p></div><div class="border border-line bg-canvas p-3 text-right"><p class="font-mono text-[8px] text-steel-500 uppercase">Peso</p><p class="mt-1 font-display text-xl font-bold {{ $isEntry ? 'text-signal' : 'text-danger' }}">{{ $isEntry ? '+' : '−' }}{{ $quantity($adjustment->peso_kg, 3) }}</p></div></div></div><a href="{{ route('mercaderia.show', $adjustment) }}" class="mt-4 inline-flex min-h-10 items-center justify-center border border-ink-950 px-4 font-mono text-[9px] font-semibold tracking-wider text-ink-950 uppercase transition hover:bg-ink-950 hover:text-white">Ver ajuste</a></article>@endforeach</div>@endif</section>

            <section class="reveal-up reveal-up-delay-1 border border-line bg-paper shadow-panel" aria-labelledby="conciliation-audit-title"><div class="border-b border-line px-5 py-5 sm:px-6"><p class="font-mono text-[9px] font-semibold tracking-[0.18em] text-signal uppercase">Documento / Auditoría</p><h2 id="conciliation-audit-title" class="mt-1 font-display text-2xl font-bold text-ink-950 uppercase">Datos del control</h2></div><dl class="grid sm:grid-cols-2"><div class="border-b border-line p-5 sm:border-r sm:p-6"><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Número</dt><dd class="mt-2 font-mono text-sm font-semibold text-ink-950">{{ $conciliation->numero_conciliacion }}</dd></div><div class="border-b border-line p-5 sm:p-6"><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Tipo</dt><dd class="mt-2 font-semibold text-ink-950">{{ $conciliation->tipo_conciliacion === 'CIERRE' ? 'Cierre operativo' : 'Conciliación extraordinaria' }}</dd></div><div class="border-b border-line p-5 sm:border-r sm:p-6"><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Realizada por</dt><dd class="mt-2 font-semibold text-ink-950">{{ $conciliation->usuario->nombreCompleto() }}</dd><dd class="mt-1 text-xs text-steel-500">{{ $conciliation->usuario->usuario }}</dd></div><div class="border-b border-line p-5 sm:p-6"><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Fecha y hora</dt><dd class="mt-2 font-semibold text-ink-950">{{ $conciliation->realizada_at->format('d/m/Y · H:i:s') }}</dd></div><div class="p-5 sm:col-span-2 sm:p-6"><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Observación</dt><dd class="mt-2 text-sm leading-6 text-ink-700">{{ $conciliation->observacion ?: 'Conciliación registrada sin observaciones.' }}</dd></div></dl></section></div>

        <aside class="grid content-start gap-6"><section class="reveal-up reveal-up-delay-2 border border-line bg-paper p-5 shadow-panel"><p class="font-mono text-[9px] font-semibold tracking-wider text-signal uppercase">Producto conciliado</p><h2 class="mt-2 font-display text-2xl font-bold text-ink-950 uppercase">{{ $conciliation->producto->nombre }}</h2><p class="mt-2 text-sm leading-6 text-steel-500">{{ $conciliation->producto->descripcion ?: 'Producto sin descripción adicional.' }}</p><div class="mt-5 grid gap-3"><a href="{{ route('mercaderia.index') }}" class="inline-flex min-h-11 items-center justify-center border border-ink-950 font-display text-xs font-bold tracking-wider text-ink-950 uppercase transition hover:bg-ink-950 hover:text-white">Ver movimientos</a><a href="{{ route('conciliaciones-mercaderia.create', ['producto' => $conciliation->producto_id]) }}" class="inline-flex min-h-11 items-center justify-center bg-ink-950 font-display text-xs font-bold tracking-wider text-white uppercase transition hover:bg-ink-800">Nuevo conteo</a></div></section><section class="reveal-up reveal-up-delay-2 border-l-4 {{ $isBalanced ? 'border-signal bg-signal-soft' : 'border-hazard bg-hazard-soft' }} p-5"><p class="font-mono text-[9px] font-semibold tracking-wider {{ $isBalanced ? 'text-signal' : 'text-ink-950' }} uppercase">Resultado operativo</p><p class="mt-2 text-sm leading-6 text-ink-700">{{ $isBalanced ? 'La existencia física coincidió exactamente con el sistema.' : 'La diferencia quedó corregida y enlazada a esta conciliación para mantener trazabilidad.' }}</p></section></aside>
    </div>
@endsection
