@extends('layouts.app')

@section('title', 'Anular beneficiado')
@section('section', 'Mercadería · Beneficiado')

@section('content')
    @php($quantity = fn (float|int|string|null $value, int $decimals = 0): string => number_format((float) ($value ?? 0), $decimals, ',', '.'))

    <header class="reveal-up border-b border-line pb-7"><p class="font-mono text-[10px] font-semibold tracking-[0.24em] text-danger uppercase">Operación irreversible / {{ $process->numero_proceso }}</p><h1 class="mt-3 font-display text-4xl leading-none font-extrabold tracking-tight text-ink-950 uppercase sm:text-5xl">Anular beneficiado</h1><p class="mt-3 max-w-3xl text-sm leading-6 text-steel-500">La anulación devolverá las aves y el peso al producto vivo y retirará los kilogramos obtenidos del producto beneficiado.</p></header>

    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_390px]">
        <form method="POST" action="{{ route('beneficiados.anulacion.store', $process) }}" data-confirm="¿Confirmas la anulación de este proceso de beneficiado?" class="reveal-up reveal-up-delay-1 border border-danger/40 bg-paper shadow-panel" novalidate>
            @csrf
            <div class="border-b border-danger/20 bg-danger-soft px-5 py-5 sm:px-6"><p class="font-mono text-[9px] font-semibold tracking-[0.18em] text-danger uppercase">Confirmación requerida</p><h2 class="mt-1 font-display text-2xl font-bold text-ink-950 uppercase">Motivo de anulación</h2></div>
            <div class="grid gap-6 p-5 sm:p-6"><div class="grid gap-4 sm:grid-cols-3"><div class="border border-line bg-canvas p-4"><p class="font-mono text-[8px] text-steel-500 uppercase">Carga</p><p class="mt-2 font-display text-xl font-bold text-ink-950 uppercase">{{ $process->cargaProveedor->numero_carga }}</p></div><div class="border border-line bg-canvas p-4"><p class="font-mono text-[8px] text-steel-500 uppercase">Vivo a devolver</p><p class="mt-2 font-display text-xl font-bold text-signal">{{ $quantity($process->cantidad_pollos) }} aves</p><p class="mt-1 text-xs text-steel-500">{{ $quantity($process->peso_origen_kg, 3) }} kg</p></div><div class="border border-line bg-canvas p-4"><p class="font-mono text-[8px] text-steel-500 uppercase">Beneficiado a retirar</p><p class="mt-2 font-display text-xl font-bold text-danger">{{ $quantity($process->peso_resultante_kg, 3) }} kg</p></div></div><x-form-field name="motivo_anulacion" label="Motivo" hint="Entre 10 y 255 caracteres" required><textarea id="motivo_anulacion" name="motivo_anulacion" rows="5" minlength="10" maxlength="255" placeholder="Explica por qué debe revertirse este proceso..." class="w-full resize-y border border-line bg-white px-4 py-3 text-sm text-ink-950 outline-none transition placeholder:text-steel-300 focus:border-danger focus:ring-2 focus:ring-danger/15" required autofocus>{{ old('motivo_anulacion') }}</textarea></x-form-field></div>
            <div class="flex flex-col-reverse gap-3 border-t border-line px-5 py-5 sm:flex-row sm:justify-end sm:px-6"><a href="{{ route('beneficiados.show', $process) }}" class="inline-flex min-h-12 items-center justify-center border border-line px-6 font-display text-sm font-bold tracking-wider text-ink-700 uppercase transition hover:border-ink-950 hover:text-ink-950">Volver</a><button type="submit" class="inline-flex min-h-12 items-center justify-center bg-danger px-7 font-display text-sm font-bold tracking-wider text-white uppercase transition hover:bg-red-700">Confirmar anulación</button></div>
        </form>

        <aside class="grid content-start gap-6"><section class="industrial-hatch panel-cut reveal-up reveal-up-delay-2 bg-ink-950 p-6 text-white shadow-panel"><p class="font-mono text-[9px] tracking-[0.2em] text-hazard uppercase">Reversión / Inventario</p><h2 class="mt-2 font-display text-2xl font-bold uppercase">Efecto del cambio</h2><div class="mt-6 grid gap-px border border-white/10 bg-white/10"><div class="bg-white/5 p-4"><p class="font-mono text-[8px] text-steel-300 uppercase">{{ $process->cargaProveedor->producto->nombre }}</p><p class="mt-2 font-display text-2xl font-bold text-signal">+ {{ $quantity($process->peso_origen_kg, 3) }} kg</p></div><div class="bg-white/5 p-4"><p class="font-mono text-[8px] text-steel-300 uppercase">{{ $process->productoDestino->nombre }}</p><p class="mt-2 font-display text-2xl font-bold text-danger">− {{ $quantity($process->peso_resultante_kg, 3) }} kg</p></div></div></section><section class="reveal-up reveal-up-delay-2 border-l-4 border-danger bg-danger-soft p-5"><p class="font-mono text-[9px] font-semibold tracking-wider text-danger uppercase">Conserva trazabilidad</p><p class="mt-2 text-sm leading-6 text-ink-700">El registro no se elimina. Quedará marcado como anulado con tu usuario, fecha y motivo.</p></section></aside>
    </div>
@endsection
