@extends('layouts.app')

@section('title', $process->numero_proceso)
@section('section', 'Mercadería · Beneficiado')

@section('content')
    @php($quantity = fn (float|int|string|null $value, int $decimals = 0): string => number_format((float) ($value ?? 0), $decimals, ',', '.'))

    <header class="reveal-up flex flex-col gap-6 border-b border-line pb-7 xl:flex-row xl:items-end xl:justify-between">
        <div><div class="flex flex-wrap items-center gap-3"><p class="font-mono text-[10px] font-semibold tracking-[0.24em] text-signal uppercase">Proceso / {{ $process->numero_proceso }}</p><span class="inline-flex border px-2.5 py-1 font-mono text-[8px] font-semibold tracking-wider uppercase {{ $process->estaAnulado() ? 'border-danger/30 bg-danger-soft text-danger' : 'border-signal/30 bg-signal-soft text-signal' }}">{{ $process->estaAnulado() ? 'Anulado' : 'Vigente' }}</span></div><h1 class="mt-3 font-display text-4xl leading-none font-extrabold tracking-tight text-ink-950 uppercase sm:text-5xl">Detalle del beneficiado</h1><p class="mt-3 text-sm text-steel-500">Registrado el {{ $process->procesado_at->format('d/m/Y') }} a las {{ $process->procesado_at->format('H:i') }} por {{ $process->procesadoPor->nombreCompleto() }}.</p></div>
        <div class="flex flex-col gap-3 sm:flex-row"><a href="{{ route('beneficiados.index') }}" class="inline-flex min-h-12 items-center justify-center border border-line px-5 font-display text-sm font-bold tracking-wider text-ink-700 uppercase transition hover:border-ink-950 hover:text-ink-950">Volver al historial</a>@if ($canCancel)<a href="{{ route('beneficiados.anulacion.create', $process) }}" class="inline-flex min-h-12 items-center justify-center border border-danger px-5 font-display text-sm font-bold tracking-wider text-danger uppercase transition hover:bg-danger hover:text-white">Anular proceso</a>@endif</div>
    </header>

    @if ($process->estaAnulado())
        <section class="mt-6 border-l-4 border-danger bg-danger-soft p-5"><p class="font-mono text-[9px] font-semibold tracking-wider text-danger uppercase">Proceso anulado</p><p class="mt-2 text-sm leading-6 text-ink-700">{{ $process->motivo_anulacion }}</p><p class="mt-2 text-xs text-steel-500">{{ $process->anulado_at->format('d/m/Y · H:i') }} · {{ $process->anuladoPor->nombreCompleto() }}</p></section>
    @elseif ($cancellationBlockReason !== null)
        <section class="mt-6 border-l-4 border-hazard bg-hazard-soft p-5"><p class="font-mono text-[9px] font-semibold tracking-wider text-ink-950 uppercase">Anulación bloqueada</p><p class="mt-2 text-sm leading-6 text-ink-700">{{ $cancellationBlockReason }}</p></section>
    @endif

    <section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Resumen del proceso">
        <x-stat-card label="Aves procesadas" :value="$quantity($process->cantidad_pollos).' aves'" :meta="$process->cargaProveedor->producto->nombre" tone="hazard" />
        <x-stat-card label="Peso vivo retirado" :value="$quantity($process->peso_origen_kg, 3).' kg'" :meta="$process->cargaProveedor->numero_carga" tone="hazard" />
        <x-stat-card label="Peso beneficiado" :value="$quantity($process->peso_resultante_kg, 3).' kg'" :meta="$process->productoDestino->nombre" tone="signal" />
        <x-stat-card label="Rendimiento" :value="$quantity($process->rendimientoPorcentaje(), 2).'%'" :meta="$quantity($process->mermaKg(), 3).' kg de merma'" tone="signal" />
    </section>

    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_390px]">
        <section class="reveal-up reveal-up-delay-1 border border-line bg-paper shadow-panel" aria-labelledby="beneficiary-trace-title">
            <div class="border-b border-line px-5 py-5 sm:px-6"><p class="font-mono text-[9px] font-semibold tracking-[0.18em] text-signal uppercase">Origen / Destino</p><h2 id="beneficiary-trace-title" class="mt-1 font-display text-2xl font-bold text-ink-950 uppercase">Trazabilidad de la conversión</h2></div>
            <div class="grid gap-px bg-line lg:grid-cols-[1fr_auto_1fr]"><article class="bg-paper p-6"><p class="font-mono text-[9px] font-semibold tracking-wider text-danger uppercase">Sale del stock vivo</p><h3 class="mt-3 font-display text-2xl font-bold text-ink-950 uppercase">{{ $process->cargaProveedor->producto->nombre }}</h3><dl class="mt-5 grid gap-4 text-sm"><div><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Carga</dt><dd class="mt-1 font-semibold text-ink-950"><a href="{{ route('cargas-proveedor.show', $process->cargaProveedor) }}" class="underline decoration-hazard/50 underline-offset-4">{{ $process->cargaProveedor->numero_carga }}</a></dd></div><div><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Proveedor</dt><dd class="mt-1 font-semibold text-ink-950">{{ $process->cargaProveedor->proveedor->nombre_razon_social }}</dd></div><div><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Saldo vivo actual</dt><dd class="mt-1 font-semibold text-ink-950">{{ $quantity($sourceBalance->pollos_disponibles) }} aves · {{ $quantity($sourceBalance->kg_disponibles, 3) }} kg</dd></div></dl></article><div class="hidden w-16 place-items-center bg-canvas lg:grid" aria-hidden="true"><span class="grid size-10 place-items-center bg-hazard font-display text-xl font-bold text-ink-950">→</span></div><article class="bg-paper p-6"><p class="font-mono text-[9px] font-semibold tracking-wider text-signal uppercase">Ingresa al stock de venta</p><h3 class="mt-3 font-display text-2xl font-bold text-ink-950 uppercase">{{ $process->productoDestino->nombre }}</h3><dl class="mt-5 grid gap-4 text-sm"><div><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Cantidad ingresada</dt><dd class="mt-1 font-semibold text-signal">+ {{ $quantity($process->peso_resultante_kg, 3) }} kg</dd></div><div><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Modalidad</dt><dd class="mt-1 font-semibold text-ink-950">Venta solo por kilogramos</dd></div><div><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Saldo disponible actual</dt><dd class="mt-1 font-semibold text-ink-950">{{ $quantity($destinationBalance->kg_disponibles, 3) }} kg</dd></div></dl></article></div>
        </section>

        <aside class="grid content-start gap-6">
            <section class="industrial-hatch panel-cut reveal-up reveal-up-delay-2 bg-ink-950 p-6 text-white shadow-panel"><p class="font-mono text-[9px] tracking-[0.2em] text-hazard uppercase">Balance / Proceso</p><h2 class="mt-2 font-display text-2xl font-bold uppercase">Rendimiento real</h2><div class="mt-6 grid gap-px border border-white/10 bg-white/10"><div class="bg-ink-950 p-4"><p class="font-mono text-[8px] text-steel-300 uppercase">Peso vivo</p><p class="mt-2 font-display text-3xl font-extrabold">{{ $quantity($process->peso_origen_kg, 3) }} kg</p></div><div class="grid grid-cols-2 gap-px bg-white/10"><div class="bg-white/5 p-4"><p class="font-mono text-[8px] text-steel-300 uppercase">Resultado</p><p class="mt-2 font-display text-2xl font-bold text-signal">{{ $quantity($process->peso_resultante_kg, 3) }}</p></div><div class="bg-white/5 p-4"><p class="font-mono text-[8px] text-steel-300 uppercase">Merma</p><p class="mt-2 font-display text-2xl font-bold text-hazard">{{ $quantity($process->mermaKg(), 3) }}</p></div></div></div></section>
            <section class="reveal-up reveal-up-delay-2 border border-line bg-paper p-5 shadow-panel"><p class="font-mono text-[9px] font-semibold tracking-wider text-signal uppercase">Observación</p><p class="mt-2 text-sm leading-6 text-steel-500">{{ $process->observacion ?: 'Sin observaciones registradas.' }}</p></section>
        </aside>
    </div>
@endsection
