@extends('layouts.app')

@section('title', 'Eliminar venta')
@section('section', 'Ventas y pesajes')

@section('content')
    @php($money = fn (float|int|string|null $value): string => 'S/ '.number_format((float) ($value ?? 0), 2, ',', '.'))
    <header class="reveal-up border-b border-line pb-7"><a href="{{ route('ventas.show', $sale) }}" class="font-mono text-[9px] font-semibold tracking-[0.18em] text-signal uppercase">← Volver a la venta</a><p class="mt-5 font-mono text-[10px] font-semibold tracking-[0.24em] text-danger uppercase">Auditoría / Eliminación</p><h1 class="mt-3 font-display text-4xl leading-none font-extrabold tracking-tight text-ink-950 uppercase sm:text-5xl">Eliminar venta</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-steel-500">La venta no se borrará físicamente: quedará anulada en el historial y la mercadería regresará automáticamente al saldo disponible.</p></header>
    <div class="mx-auto mt-6 grid max-w-5xl gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><form method="POST" action="{{ route('ventas.anulacion.store', $sale) }}" data-confirm="¿Confirmas la eliminación de esta venta?" class="reveal-up reveal-up-delay-1 border border-line bg-paper shadow-panel" novalidate>@csrf<div class="border-b border-line px-5 py-5 sm:px-6"><p class="font-mono text-[9px] font-semibold tracking-[0.18em] text-danger uppercase">Motivo obligatorio</p><h2 class="mt-1 font-display text-2xl font-bold text-ink-950 uppercase">Justificación</h2></div><div class="p-5 sm:p-6"><x-form-field name="motivo_anulacion" label="Motivo de la eliminación" hint="Entre 10 y 255 caracteres" required><textarea id="motivo_anulacion" name="motivo_anulacion" rows="5" minlength="10" maxlength="255" class="w-full resize-y border border-line bg-white px-4 py-3 text-sm text-ink-950 outline-none focus:border-danger" placeholder="Explica por qué debe eliminarse la venta..." required autofocus>{{ old('motivo_anulacion') }}</textarea></x-form-field><div class="mt-5 border-l-4 border-danger bg-danger-soft px-4 py-3 text-sm leading-6 text-danger">No se borrarán el detalle ni los pesajes. El sistema conservará usuario, fecha y motivo, y marcará la venta como anulada.</div></div><div class="flex flex-col-reverse gap-3 border-t border-line px-5 py-5 sm:flex-row sm:justify-end sm:px-6"><a href="{{ route('ventas.show', $sale) }}" class="inline-flex min-h-12 items-center justify-center border border-line px-6 font-display text-sm font-bold tracking-wider text-ink-700 uppercase">Conservar venta</a><button type="submit" class="inline-flex min-h-12 items-center justify-center bg-danger px-7 font-display text-sm font-bold tracking-wider text-white uppercase">Eliminar venta</button></div></form><aside class="industrial-hatch panel-cut reveal-up reveal-up-delay-2 bg-ink-950 p-6 text-white shadow-panel"><p class="font-mono text-[9px] tracking-[0.2em] text-hazard uppercase">Venta seleccionada</p><h2 class="mt-2 font-mono text-sm font-semibold">{{ $sale->numero_venta }}</h2><p class="mt-5 font-display text-4xl font-extrabold">{{ $money($totals->total_venta) }}</p><div class="mt-6 border-t border-white/10 pt-5"><p class="font-display text-xl font-bold uppercase">{{ $sale->cliente?->nombres_razon_social ?? 'Sin cliente identificado' }}</p><p class="mt-2 font-mono text-[9px] tracking-wider text-steel-300 uppercase">{{ number_format((float) $totals->cantidad_pollos, 0, ',', '.') }} aves · {{ number_format((float) $totals->peso_neto_kg, 3, ',', '.') }} kg</p><p class="mt-3 text-sm text-steel-300">Registrada por {{ $sale->usuario->nombreCompleto() }} el {{ $sale->fecha_venta->format('d/m/Y \\a \\l\\a\\s H:i') }}.</p></div></aside></div>
@endsection
