@extends('layouts.app')

@section('title', 'Ventas y pesajes')
@section('section', 'Ventas y pesajes')

@section('content')
    @php
        $money = fn (float|int|string|null $value): string => 'S/ '.number_format((float) ($value ?? 0), 2, ',', '.');
        $quantity = fn (float|int|string|null $value, int $decimals = 0): string => number_format((float) ($value ?? 0), $decimals, ',', '.');
    @endphp

    <header class="reveal-up flex flex-col gap-6 border-b border-line pb-7 xl:flex-row xl:items-end xl:justify-between">
        <div class="max-w-3xl"><p class="font-mono text-[10px] font-semibold tracking-[0.24em] text-signal uppercase">Comercial / Despachos</p><h1 class="mt-3 font-display text-4xl leading-none font-extrabold tracking-tight text-ink-950 uppercase sm:text-5xl">Ventas y pesajes</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-steel-500">Consulta las salidas de mercadería, el peso facturado y el saldo por cobrar de cada operación.</p></div>
        @if ($authenticatedUser?->tienePermiso('VENTAS_REGISTRAR'))<a href="{{ route('ventas.create') }}" class="group inline-flex min-h-12 items-center justify-between gap-5 bg-ink-950 px-5 font-display text-sm font-bold tracking-wider text-white uppercase transition hover:bg-ink-800">Registrar venta<span class="grid size-7 place-items-center bg-hazard text-lg text-ink-950 transition group-hover:rotate-90">+</span></a>@endif
    </header>

    <section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Resumen de ventas del día">
        <x-stat-card label="Ventas de hoy" :value="$quantity($todaySummary?->cantidad_ventas)" meta="Operaciones activas" tone="hazard"><x-slot:icon><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 7h16v12H4V7Zm3-3h10v3M8 12h8" /></svg></x-slot:icon></x-stat-card>
        <x-stat-card label="Aves vendidas" :value="$quantity($todaySummary?->pollos_vendidos)" :meta="$quantity($todaySummary?->kg_vendidos, 3).' kg netos'" tone="signal"><x-slot:icon><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 15c0-4 3-7 7-7h5l2 3-3 2v5H5v-3Z" /><circle cx="14" cy="10" r="1" /></svg></x-slot:icon></x-stat-card>
        <x-stat-card label="Facturación" :value="$money($todaySummary?->total_ventas)" meta="Total vendido hoy"><x-slot:icon><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3v18m5-14H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H7" /></svg></x-slot:icon></x-stat-card>
        <x-stat-card label="Por cobrar" :value="$money($todaySummary?->saldo_por_cobrar)" meta="Saldo pendiente de hoy" tone="danger"><x-slot:icon><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" /></svg></x-slot:icon></x-stat-card>
    </section>

    <form method="GET" action="{{ route('ventas.index') }}" class="reveal-up reveal-up-delay-1 mt-6 grid gap-3 border border-line bg-paper p-4 shadow-sm lg:grid-cols-[minmax(0,1fr)_190px_210px_auto]">
        <div class="relative"><label for="sale-search" class="sr-only">Buscar venta</label><svg class="pointer-events-none absolute top-1/2 left-4 size-4 -translate-y-1/2 text-steel-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="11" cy="11" r="7" /><path d="m20 20-4-4" /></svg><input id="sale-search" name="buscar" type="search" value="{{ $search }}" placeholder="Venta, cliente o documento..." class="min-h-12 w-full border border-line bg-white pr-4 pl-11 text-sm text-ink-950 outline-none placeholder:text-steel-300 focus:border-ink-950"></div>
        <select name="estado" aria-label="Estado de la venta" class="min-h-12 border border-line bg-white px-4 text-sm font-semibold text-ink-700 outline-none focus:border-ink-950"><option value="activas" @selected($status === 'activas')>Solo activas</option><option value="anuladas" @selected($status === 'anuladas')>Solo anuladas</option><option value="todas" @selected($status === 'todas')>Todas</option></select>
        <input name="fecha" type="date" value="{{ $date }}" max="{{ today()->toDateString() }}" aria-label="Fecha de venta" class="min-h-12 border border-line bg-white px-4 text-sm font-semibold text-ink-700 outline-none focus:border-ink-950">
        <div class="flex gap-2"><button type="submit" class="inline-flex min-h-12 flex-1 items-center justify-center bg-ink-950 px-5 font-display text-sm font-bold tracking-wider text-white uppercase lg:flex-none">Filtrar</button>@if ($search !== '' || $status !== 'activas' || $date !== today()->toDateString())<a href="{{ route('ventas.index') }}" class="inline-flex min-h-12 items-center justify-center border border-line px-4 text-xs font-semibold text-steel-500" aria-label="Limpiar filtros">×</a>@endif</div>
    </form>

    <section class="reveal-up reveal-up-delay-2 mt-6 overflow-hidden border border-line bg-paper shadow-panel" aria-labelledby="sales-history-title">
        <div class="flex items-center justify-between gap-4 border-b border-line px-5 py-5 sm:px-6"><div><p class="font-mono text-[9px] font-semibold tracking-[0.18em] text-signal uppercase">Control / Historial</p><h2 id="sales-history-title" class="mt-1 font-display text-2xl font-bold text-ink-950 uppercase">Operaciones registradas</h2></div><span class="border border-line px-2.5 py-1 font-mono text-[9px] text-steel-500 uppercase">{{ $sales->total() }} registros</span></div>
        @if ($sales->isEmpty())
            <x-empty-state title="No hay ventas registradas" description="Las ventas y sus pesajes de salida aparecerán en este historial." :action-href="$authenticatedUser?->tienePermiso('VENTAS_REGISTRAR') ? route('ventas.create') : null" action-label="Registrar primera venta"><x-slot:icon><svg class="size-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M4 7h16v12H4V7Zm3-3h10v3M8 12h8" /></svg></x-slot:icon></x-empty-state>
        @else
            <div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[1080px] border-collapse text-left"><thead class="bg-canvas font-mono text-[9px] tracking-[0.16em] text-steel-500 uppercase"><tr><th class="px-6 py-3 font-semibold">Venta</th><th class="px-6 py-3 font-semibold">Cliente</th><th class="px-6 py-3 text-right font-semibold">Salida</th><th class="px-6 py-3 text-right font-semibold">Total</th><th class="px-6 py-3 font-semibold">Cobro</th><th class="px-6 py-3 text-right font-semibold">Acción</th></tr></thead><tbody class="divide-y divide-line">@foreach ($sales as $sale)@php($total = $totals->get($sale->id))@php($balance = $balances->get($sale->id))<tr class="transition hover:bg-hazard-soft/20"><td class="px-6 py-4"><p class="font-mono text-xs font-semibold text-ink-950">{{ $sale->numero_venta }}</p><p class="mt-1 text-xs text-steel-500">{{ $sale->fecha_venta->format('d/m/Y · H:i') }} · {{ $sale->usuario->nombreCompleto() }}</p></td><td class="px-6 py-4"><p class="font-semibold text-ink-950">{{ $sale->cliente?->nombres_razon_social ?? 'Sin cliente identificado' }}</p><p class="mt-1 text-xs text-steel-500">{{ $sale->cliente?->nro_documento ?: 'Venta directa' }}</p></td><td class="px-6 py-4 text-right"><p class="font-mono text-xs font-semibold text-ink-950">{{ $quantity($total?->cantidad_pollos) }} aves</p><p class="mt-1 text-xs text-steel-500">{{ $quantity($total?->peso_neto_kg, 3) }} kg</p></td><td class="px-6 py-4 text-right font-display text-xl font-bold {{ $sale->estaAnulada() ? 'text-steel-500 line-through' : 'text-ink-950' }}">{{ $money($total?->total_venta) }}</td><td class="px-6 py-4"><span class="inline-flex border px-2.5 py-1 font-mono text-[8px] font-semibold tracking-wider uppercase {{ $sale->estaAnulada() ? 'border-danger/30 bg-danger-soft text-danger' : ($balance?->estado_pago === 'SALDADA' ? 'border-signal/30 bg-signal-soft text-signal' : 'border-hazard/40 bg-hazard-soft text-ink-950') }}">{{ $sale->estaAnulada() ? 'Anulada' : ($balance?->estado_pago ?? 'Pendiente') }}</span><p class="mt-1 text-xs text-steel-500">Saldo {{ $money($balance?->saldo_pendiente) }}</p></td><td class="px-6 py-4 text-right"><a href="{{ route('ventas.show', $sale) }}" class="inline-flex min-h-9 items-center border border-line px-3 font-mono text-[9px] font-semibold tracking-wider text-ink-700 uppercase transition hover:border-ink-950 hover:bg-ink-950 hover:text-white">Ver detalle</a></td></tr>@endforeach</tbody></table></div>
            <div class="divide-y divide-line md:hidden">@foreach ($sales as $sale)@php($total = $totals->get($sale->id))@php($balance = $balances->get($sale->id))<article class="p-5"><div class="flex items-start justify-between gap-4"><div><p class="font-mono text-xs font-semibold text-ink-950">{{ $sale->numero_venta }}</p><p class="mt-1 text-xs text-steel-500">{{ $sale->fecha_venta->format('d/m/Y · H:i') }}</p></div><span class="border px-2 py-1 font-mono text-[8px] font-semibold uppercase {{ $sale->estaAnulada() ? 'border-danger/30 bg-danger-soft text-danger' : 'border-hazard/40 bg-hazard-soft text-ink-950' }}">{{ $sale->estaAnulada() ? 'Anulada' : ($balance?->estado_pago ?? 'Pendiente') }}</span></div><p class="mt-4 font-semibold text-ink-950">{{ $sale->cliente?->nombres_razon_social ?? 'Sin cliente identificado' }}</p><div class="mt-4 grid grid-cols-2 gap-3 border-y border-line py-4"><div><p class="font-mono text-[8px] text-steel-500 uppercase">Salida</p><p class="mt-1 font-semibold text-ink-950">{{ $quantity($total?->cantidad_pollos) }} aves · {{ $quantity($total?->peso_neto_kg, 3) }} kg</p></div><div class="text-right"><p class="font-mono text-[8px] text-steel-500 uppercase">Total</p><p class="mt-1 font-display text-xl font-bold text-ink-950">{{ $money($total?->total_venta) }}</p></div></div><a href="{{ route('ventas.show', $sale) }}" class="mt-4 inline-flex min-h-10 w-full items-center justify-center border border-ink-950 font-mono text-[9px] font-semibold tracking-wider text-ink-950 uppercase">Ver detalle</a></article>@endforeach</div>
            <x-catalog-pagination :paginator="$sales" />
        @endif
    </section>
@endsection
