@php
    $inputClasses = 'min-h-12 w-full border border-line bg-white px-4 text-sm text-ink-950 outline-none transition placeholder:text-steel-300 focus:border-ink-950 focus:ring-2 focus:ring-hazard/40';
@endphp

<div class="grid gap-6">
    <x-form-field name="nombre_razon_social" label="Nombre o razón social" required>
        <input id="nombre_razon_social" name="nombre_razon_social" type="text" value="{{ old('nombre_razon_social', $supplier?->nombre_razon_social) }}" maxlength="150" autocomplete="organization" required class="{{ $inputClasses }}" placeholder="Empresa o nombre completo" @error('nombre_razon_social') aria-invalid="true" aria-describedby="nombre_razon_social-error" @enderror>
    </x-form-field>
    <div class="grid gap-5 sm:grid-cols-[220px_minmax(0,1fr)]">
        <x-form-field name="tipo_documento_id" label="Tipo de documento" hint="Opcional"><div class="relative grid"><select id="tipo_documento_id" name="tipo_documento_id" data-document-type class="{{ $inputClasses }} col-start-1 row-start-1 appearance-none pr-10" @error('tipo_documento_id') aria-invalid="true" aria-describedby="tipo_documento_id-error" @enderror><option value="">Sin documento</option>@foreach ($documentTypes as $documentType)<option value="{{ $documentType->id }}" data-max="{{ $documentType->longitud_maxima }}" @selected((string) old('tipo_documento_id', $supplier?->tipo_documento_id) === (string) $documentType->id)>{{ $documentType->codigo }} · {{ $documentType->nombre }}</option>@endforeach</select><svg class="pointer-events-none col-start-1 row-start-1 mr-4 size-4 self-center justify-self-end text-steel-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="m7 10 5 5 5-5" /></svg></div></x-form-field>
        <x-form-field name="nro_documento" label="Número de documento" hint="Según el tipo seleccionado"><input id="nro_documento" name="nro_documento" type="text" value="{{ old('nro_documento', $supplier?->nro_documento) }}" maxlength="20" data-document-number class="{{ $inputClasses }} font-mono uppercase" placeholder="Número de identificación" @error('nro_documento') aria-invalid="true" aria-describedby="nro_documento-error" @enderror></x-form-field>
    </div>
    <div class="grid gap-5 sm:grid-cols-2">
        <x-form-field name="telefono" label="Teléfono" hint="Opcional · 9 dígitos"><input id="telefono" name="telefono" type="tel" value="{{ old('telefono', $supplier?->telefono) }}" maxlength="9" inputmode="numeric" pattern="[0-9]{9}" data-digits-only autocomplete="tel" class="{{ $inputClasses }}" placeholder="Ej. 999999999" @error('telefono') aria-invalid="true" aria-describedby="telefono-error" @enderror></x-form-field>
        <x-form-field name="numero_cuenta" label="Número de cuenta / CCI" hint="Opcional · para pagos"><input id="numero_cuenta" name="numero_cuenta" type="text" value="{{ old('numero_cuenta', $supplier?->numero_cuenta) }}" maxlength="100" autocomplete="off" class="{{ $inputClasses }} font-mono uppercase" placeholder="Banco, cuenta o CCI" @error('numero_cuenta') aria-invalid="true" aria-describedby="numero_cuenta-error" @enderror></x-form-field>
    </div>
    <div class="grid gap-5">
        <x-form-field name="direccion" label="Dirección" hint="Opcional"><input id="direccion" name="direccion" type="text" value="{{ old('direccion', $supplier?->direccion) }}" maxlength="255" autocomplete="street-address" class="{{ $inputClasses }}" placeholder="Dirección fiscal o planta" @error('direccion') aria-invalid="true" aria-describedby="direccion-error" @enderror></x-form-field>
    </div>
    <label class="flex cursor-pointer items-center justify-between gap-4 border border-line bg-canvas px-4 py-3"><span><span class="block text-sm font-semibold text-ink-950">Proveedor activo</span><span class="mt-0.5 block text-xs text-steel-500">Disponible para nuevas cargas y pagos.</span></span><input type="hidden" name="activo" value="0"><input name="activo" type="checkbox" value="1" class="size-5 accent-signal" @checked((bool) old('activo', $supplier?->activo ?? true))></label>
    <div class="flex flex-col-reverse gap-3 border-t border-line pt-6 sm:flex-row sm:items-center sm:justify-between"><a href="{{ route('proveedores.index') }}" class="inline-flex min-h-11 items-center justify-center border border-line px-5 text-xs font-semibold tracking-wider text-ink-700 uppercase transition hover:border-ink-950">Cancelar</a><button type="submit" class="inline-flex min-h-11 items-center justify-center bg-ink-950 px-7 font-display text-sm font-bold tracking-wider text-white uppercase transition hover:bg-ink-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-hazard">{{ $submitLabel }}</button></div>
</div>
