@php
    $inputClasses = 'min-h-12 w-full border border-line bg-white px-4 text-sm text-ink-950 outline-none transition placeholder:text-steel-300 focus:border-ink-950 focus:ring-2 focus:ring-hazard/40';
@endphp

<div class="grid gap-6">
    <x-form-field name="nombre" label="Nombre del producto" hint="Se guardará en mayúsculas" required><input id="nombre" name="nombre" type="text" value="{{ old('nombre', $product?->nombre) }}" maxlength="100" required class="{{ $inputClasses }} uppercase" placeholder="Ej. POLLO BENEFICIADO" @error('nombre') aria-invalid="true" aria-describedby="nombre-error" @enderror></x-form-field>
    <x-form-field name="unidad_medida_id" label="Unidad de medida" required><div class="relative grid"><select id="unidad_medida_id" name="unidad_medida_id" required class="{{ $inputClasses }} col-start-1 row-start-1 appearance-none pr-10" @error('unidad_medida_id') aria-invalid="true" aria-describedby="unidad_medida_id-error" @enderror><option value="">Selecciona una unidad</option>@foreach ($measurementUnits as $measurementUnit)<option value="{{ $measurementUnit->id }}" @selected((string) old('unidad_medida_id', $product?->unidad_medida_id) === (string) $measurementUnit->id)>{{ $measurementUnit->nombre }} · {{ $measurementUnit->simbolo }}</option>@endforeach</select><svg class="pointer-events-none col-start-1 row-start-1 mr-4 size-4 self-center justify-self-end text-steel-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="m7 10 5 5 5-5" /></svg></div></x-form-field>
    <x-form-field name="modalidad_venta" label="Modalidad de venta" hint="Define los datos solicitados en Ventas y pesajes" required><div class="relative grid"><select id="modalidad_venta" name="modalidad_venta" required class="{{ $inputClasses }} col-start-1 row-start-1 appearance-none pr-10" @error('modalidad_venta') aria-invalid="true" aria-describedby="modalidad_venta-error" @enderror><option value="">Selecciona una modalidad</option>@foreach ($saleModes as $value => $label)<option value="{{ $value }}" @selected(old('modalidad_venta', $product?->modalidad_venta ?? \App\Models\Producto::MODALIDAD_PESAJE_VIVO) === $value)>{{ $label }}</option>@endforeach</select><svg class="pointer-events-none col-start-1 row-start-1 mr-4 size-4 self-center justify-self-end text-steel-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="m7 10 5 5 5-5" /></svg></div></x-form-field>
    <x-form-field name="descripcion" label="Descripción" hint="Máximo 255 caracteres"><textarea id="descripcion" name="descripcion" rows="4" maxlength="255" class="{{ $inputClasses }} resize-y py-3" placeholder="Características o presentación del producto" @error('descripcion') aria-invalid="true" aria-describedby="descripcion-error" @enderror>{{ old('descripcion', $product?->descripcion) }}</textarea></x-form-field>
    <label class="flex cursor-pointer items-center justify-between gap-4 border border-line bg-canvas px-4 py-3"><span><span class="block text-sm font-semibold text-ink-950">Producto activo</span><span class="mt-0.5 block text-xs text-steel-500">Disponible para precios y nuevas operaciones.</span></span><input type="hidden" name="activo" value="0"><input name="activo" type="checkbox" value="1" class="size-5 accent-signal" @checked((bool) old('activo', $product?->activo ?? true))></label>
    <div class="flex flex-col-reverse gap-3 border-t border-line pt-6 sm:flex-row sm:items-center sm:justify-between"><a href="{{ route('productos.index') }}" class="inline-flex min-h-11 items-center justify-center border border-line px-5 text-xs font-semibold tracking-wider text-ink-700 uppercase transition hover:border-ink-950">Cancelar</a><button type="submit" class="inline-flex min-h-11 items-center justify-center bg-ink-950 px-7 font-display text-sm font-bold tracking-wider text-white uppercase transition hover:bg-ink-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-hazard">{{ $submitLabel }}</button></div>
</div>
