@extends('layouts.app')

@section('title', 'Anular ajuste de mercadería')
@section('section', 'Mercadería')

@section('content')
    @php
        $quantity = fn (float|int|string|null $value, int $decimals = 0): string => number_format((float) ($value ?? 0), $decimals, ',', '.');
        $isEntry = $adjustment->tipoAjuste->naturaleza === 'ENTRADA';
    @endphp

    <header class="reveal-up border-b border-line pb-7"><a href="{{ route('mercaderia.show', $adjustment) }}" class="font-mono text-[9px] font-semibold tracking-[0.18em] text-signal uppercase transition hover:text-ink-950">← Volver al ajuste</a><p class="mt-5 font-mono text-[10px] font-semibold tracking-[0.24em] text-danger uppercase">Auditoría / Corrección</p><h1 class="mt-3 font-display text-4xl leading-none font-extrabold tracking-tight text-ink-950 uppercase sm:text-5xl">Anular ajuste</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-steel-500">El registro se conservará para auditoría, pero dejará de afectar la existencia actual del producto.</p></header>

    <div class="mx-auto mt-6 grid max-w-5xl gap-6 lg:grid-cols-[minmax(0,1fr)_360px]">
        <form method="POST" action="{{ route('mercaderia.anulacion.store', $adjustment) }}" data-confirm="¿Confirmas la anulación de este ajuste? La existencia de mercadería será recalculada." class="reveal-up reveal-up-delay-1 border border-line bg-paper shadow-panel" novalidate>
            @csrf
            <div class="border-b border-line px-5 py-5 sm:px-6"><p class="font-mono text-[9px] font-semibold tracking-[0.18em] text-danger uppercase">Motivo obligatorio</p><h2 class="mt-1 font-display text-2xl font-bold text-ink-950 uppercase">Justificación de la anulación</h2></div>
            <div class="p-5 sm:p-6"><x-form-field name="motivo_anulacion" label="Motivo" hint="Entre 10 y 255 caracteres" required><textarea id="motivo_anulacion" name="motivo_anulacion" rows="5" minlength="10" maxlength="255" placeholder="Explica por qué debe anularse este movimiento..." class="w-full resize-y border border-line bg-white px-4 py-3 text-sm text-ink-950 outline-none transition placeholder:text-steel-300 focus:border-danger focus:ring-2 focus:ring-danger/15" required autofocus>{{ old('motivo_anulacion') }}</textarea></x-form-field><div class="mt-5 border-l-4 border-danger bg-danger-soft px-4 py-3 text-sm leading-6 text-danger">No se eliminará el ajuste. Se guardarán el usuario, la fecha y el motivo de anulación.</div><div class="mt-5 border border-line bg-canvas p-4"><p class="font-mono text-[9px] font-semibold tracking-wider text-steel-500 uppercase">Impacto en el saldo</p><p class="mt-2 text-sm leading-6 text-ink-700">Al anular esta {{ $isEntry ? 'entrada, se descontarán' : 'salida, se devolverán' }} <strong>{{ $quantity($adjustment->cantidad_pollos) }} aves</strong> y <strong>{{ $quantity($adjustment->peso_kg, 3) }} kg</strong> al cálculo actual.</p></div></div>
            <div class="flex flex-col-reverse gap-3 border-t border-line px-5 py-5 sm:flex-row sm:justify-end sm:px-6"><a href="{{ route('mercaderia.show', $adjustment) }}" class="inline-flex min-h-12 items-center justify-center border border-line px-6 font-display text-sm font-bold tracking-wider text-ink-700 uppercase transition hover:border-ink-950 hover:text-ink-950">Conservar ajuste</a><button type="submit" class="inline-flex min-h-12 items-center justify-center bg-danger px-7 font-display text-sm font-bold tracking-wider text-white uppercase transition hover:bg-red-700">Confirmar anulación</button></div>
        </form>

        <aside class="industrial-hatch panel-cut reveal-up reveal-up-delay-2 bg-ink-950 p-6 text-white shadow-panel"><p class="font-mono text-[9px] tracking-[0.2em] text-hazard uppercase">Ajuste seleccionado</p><h2 class="mt-2 font-mono text-sm font-semibold">{{ $adjustment->numero_ajuste }}</h2><p class="mt-5 font-display text-3xl font-extrabold uppercase {{ $isEntry ? 'text-signal' : 'text-danger' }}">{{ $adjustment->tipoAjuste->nombre }}</p><div class="mt-5 grid grid-cols-2 gap-px border border-white/10 bg-white/10"><div class="bg-ink-950 p-4"><p class="font-mono text-[8px] text-steel-300 uppercase">Aves</p><p class="mt-2 font-display text-2xl font-bold">{{ $quantity($adjustment->cantidad_pollos) }}</p></div><div class="bg-ink-950 p-4"><p class="font-mono text-[8px] text-steel-300 uppercase">Peso</p><p class="mt-2 font-display text-2xl font-bold">{{ $quantity($adjustment->peso_kg, 3) }}</p><p class="text-xs text-steel-300">kg</p></div></div><div class="mt-6 border-t border-white/10 pt-5"><p class="font-display text-xl font-bold uppercase">{{ $adjustment->producto->nombre }}</p><p class="mt-3 text-sm text-steel-300">Registrado por {{ $adjustment->usuario->nombreCompleto() }} el {{ $adjustment->fecha_ajuste->format('d/m/Y \a \l\a\s H:i') }}.</p></div></aside>
    </div>
@endsection
