@extends('layouts.app')

@section('title', 'Mercadería')
@section('section', 'Mercadería')

@section('content')
    @php
        $quantity = fn (float|int|string|null $value, int $decimals = 0): string => number_format((float) ($value ?? 0), $decimals, ',', '.');
    @endphp

    <header class="reveal-up flex flex-col gap-6 border-b border-line pb-7 xl:flex-row xl:items-end xl:justify-between">
        <div class="max-w-3xl"><p class="font-mono text-[10px] font-semibold tracking-[0.24em] text-signal uppercase">Inventario / Control físico</p><h1 class="mt-3 font-display text-4xl leading-none font-extrabold tracking-tight text-ink-950 uppercase sm:text-5xl">Mercadería</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-steel-500">Consulta existencias y registra mermas, consumos, descartes o correcciones con trazabilidad completa.</p></div>
        <div class="flex flex-col gap-3 sm:flex-row sm:flex-wrap sm:items-stretch"><div class="flex min-h-12 items-center gap-3 border border-line bg-paper px-4 shadow-sm"><span class="font-display text-3xl font-extrabold text-ink-950">{{ $adjustments->total() }}</span><span class="font-mono text-[9px] leading-4 tracking-wider text-steel-500 uppercase">Ajustes en<br>historial</span></div>@if ($authenticatedUser?->tienePermiso('MERCADERIA_AJUSTAR'))<a href="{{ route('beneficiados.create') }}" class="inline-flex min-h-12 items-center justify-center border border-ink-950 px-5 font-display text-sm font-bold tracking-wider text-ink-950 uppercase transition hover:bg-ink-950 hover:text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-hazard">Registrar beneficiado</a><a href="{{ route('mercaderia.create') }}" class="group inline-flex min-h-12 items-center justify-between gap-5 bg-ink-950 px-5 font-display text-sm font-bold tracking-wider text-white uppercase transition hover:bg-ink-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-hazard">Registrar ajuste<span class="grid size-7 place-items-center bg-hazard text-lg leading-none text-ink-950 transition group-hover:rotate-90" aria-hidden="true">+</span></a>@endif</div>
    </header>

    <section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Resumen de mercadería">
        <x-stat-card label="Stock actual" :value="$quantity($totalStockBirds).' aves'" :meta="$quantity($totalStockKilograms, 3).' kg disponibles'" tone="signal"><x-slot:icon><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="m4 7 8-4 8 4-8 4-8-4Z" /><path d="m4 7v10l8 4 8-4V7m-8 4v10" /></svg></x-slot:icon></x-stat-card>
        <x-stat-card label="Ajustes de hoy" :value="$quantity($todaySummary?->cantidad_ajustes)" :meta="$quantity($todaySummary?->cantidad_anulados).' anulados'" tone="hazard"><x-slot:icon><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M4 7h16v12H4V7Zm3-3h10v3" /><path d="m9 15 6-6m-5 0h5v5" /></svg></x-slot:icon></x-stat-card>
        <x-stat-card label="Entradas por ajuste" :value="$quantity($todaySummary?->pollos_entrada).' aves'" :meta="$quantity($todaySummary?->kg_entrada, 3).' kg hoy'" tone="signal"><x-slot:icon><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M12 20V4m-6 6 6-6 6 6" /></svg></x-slot:icon></x-stat-card>
        <x-stat-card label="Salidas por ajuste" :value="$quantity($todaySummary?->pollos_salida).' aves'" :meta="$quantity($todaySummary?->kg_salida, 3).' kg hoy'" :tone="$productsToReview > 0 ? 'danger' : 'default'"><x-slot:icon><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M12 4v16m6-6-6 6-6-6" /></svg></x-slot:icon></x-stat-card>
    </section>

    <section class="reveal-up reveal-up-delay-1 mt-6 border border-line bg-paper shadow-panel" aria-labelledby="stock-current-title">
        <div class="flex flex-col gap-3 border-b border-line px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><p class="font-mono text-[9px] font-semibold tracking-[0.18em] text-signal uppercase">Existencia / Ahora</p><h2 id="stock-current-title" class="mt-1 font-display text-2xl font-bold text-ink-950 uppercase">Saldo por producto</h2></div><span class="self-start border px-2.5 py-1 font-mono text-[9px] uppercase {{ $productsToReview > 0 ? 'border-danger/30 bg-danger-soft text-danger' : 'border-signal/30 bg-signal-soft text-signal' }}">{{ $productsToReview > 0 ? $productsToReview.' por revisar' : 'Saldos conformes' }}</span></div>
        @if ($stockBalances->isEmpty())
            <div class="p-8 text-center text-sm text-steel-500">No hay productos activos para controlar.</div>
        @else
            <div class="grid gap-px bg-line sm:grid-cols-2 xl:grid-cols-3">
                @foreach ($stockBalances as $balance)
                    <article class="bg-paper p-5 transition hover:bg-hazard-soft/20"><div class="flex items-start justify-between gap-4"><div><p class="font-display text-xl font-bold text-ink-950 uppercase">{{ $balance->producto }}</p><p class="mt-1 font-mono text-[8px] tracking-wider text-steel-500 uppercase">Producto #{{ $balance->producto_id }}</p></div><span class="size-2.5 {{ $balance->requiere_revision ? 'bg-danger' : 'bg-signal' }}" title="{{ $balance->requiere_revision ? 'Requiere revisión' : 'Conforme' }}"></span></div><div class="mt-5 grid grid-cols-2 gap-3"><div class="border border-line bg-canvas p-3"><p class="font-mono text-[8px] text-steel-500 uppercase">Aves</p><p class="mt-1 font-display text-2xl font-extrabold {{ $balance->pollos_disponibles < 0 ? 'text-danger' : 'text-ink-950' }}">{{ $quantity($balance->pollos_disponibles) }}</p></div><div class="border border-line bg-canvas p-3"><p class="font-mono text-[8px] text-steel-500 uppercase">Peso</p><p class="mt-1 font-display text-2xl font-extrabold {{ $balance->kg_disponibles < 0 ? 'text-danger' : 'text-ink-950' }}">{{ $quantity($balance->kg_disponibles, 3) }} kg</p></div></div>@if ($authenticatedUser?->tienePermiso('MERCADERIA_AJUSTAR'))<a href="{{ route('mercaderia.create', ['producto' => $balance->producto_id]) }}" class="mt-4 inline-flex min-h-10 w-full items-center justify-center border border-line font-mono text-[9px] font-semibold tracking-wider text-ink-700 uppercase transition hover:border-ink-950 hover:bg-ink-950 hover:text-white">Ajustar producto</a>@endif</article>
                @endforeach
            </div>
        @endif
    </section>

    <form method="GET" action="{{ route('mercaderia.index') }}" class="reveal-up reveal-up-delay-1 mt-6 grid gap-3 border border-line bg-paper p-4 shadow-sm xl:grid-cols-[minmax(0,1fr)_170px_170px_190px_auto]">
        <div class="relative"><label for="adjustment-search" class="sr-only">Buscar ajuste</label><svg class="pointer-events-none absolute top-1/2 left-4 size-4 -translate-y-1/2 text-steel-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="11" cy="11" r="7" /><path d="m20 20-4-4" /></svg><input id="adjustment-search" name="buscar" type="search" value="{{ $search }}" placeholder="Ajuste, producto, tipo o motivo..." class="min-h-12 w-full border border-line bg-white pr-4 pl-11 text-sm text-ink-950 outline-none transition placeholder:text-steel-300 focus:border-ink-950 focus:ring-2 focus:ring-hazard/40"></div>
        <div><label for="adjustment-nature" class="sr-only">Naturaleza</label><select id="adjustment-nature" name="naturaleza" class="min-h-12 w-full border border-line bg-white px-4 text-sm font-semibold text-ink-700 outline-none transition focus:border-ink-950 focus:ring-2 focus:ring-hazard/40"><option value="">Entradas y salidas</option><option value="ENTRADA" @selected($nature === 'ENTRADA')>Solo entradas</option><option value="SALIDA" @selected($nature === 'SALIDA')>Solo salidas</option></select></div>
        <div><label for="adjustment-status" class="sr-only">Estado</label><select id="adjustment-status" name="estado" class="min-h-12 w-full border border-line bg-white px-4 text-sm font-semibold text-ink-700 outline-none transition focus:border-ink-950 focus:ring-2 focus:ring-hazard/40"><option value="vigentes" @selected($status === 'vigentes')>Solo vigentes</option><option value="anulados" @selected($status === 'anulados')>Solo anulados</option><option value="todos" @selected($status === 'todos')>Todos</option></select></div>
        <div><label for="adjustment-date" class="sr-only">Fecha</label><input id="adjustment-date" name="fecha" type="date" value="{{ $date }}" max="{{ today()->toDateString() }}" class="min-h-12 w-full border border-line bg-white px-4 text-sm font-semibold text-ink-700 outline-none transition focus:border-ink-950 focus:ring-2 focus:ring-hazard/40"></div>
        <div class="flex gap-2"><button type="submit" class="inline-flex min-h-12 flex-1 items-center justify-center bg-ink-950 px-5 font-display text-sm font-bold tracking-wider text-white uppercase transition hover:bg-ink-800 xl:flex-none">Filtrar</button>@if ($search !== '' || $status !== 'vigentes' || $date !== today()->toDateString() || $nature !== null)<a href="{{ route('mercaderia.index') }}" class="inline-flex min-h-12 items-center justify-center border border-line px-4 text-xs font-semibold text-steel-500 uppercase transition hover:border-ink-950 hover:text-ink-950" aria-label="Limpiar filtros">×</a>@endif</div>
    </form>

    <section class="reveal-up reveal-up-delay-2 mt-6 overflow-hidden border border-line bg-paper shadow-panel" aria-labelledby="adjustment-history-title">
        <div class="flex items-center justify-between gap-4 border-b border-line px-5 py-5 sm:px-6"><div><p class="font-mono text-[9px] font-semibold tracking-[0.18em] text-hazard uppercase">Auditoría / Historial</p><h2 id="adjustment-history-title" class="mt-1 font-display text-2xl font-bold text-ink-950 uppercase">Ajustes registrados</h2></div><span class="border border-line px-2.5 py-1 font-mono text-[9px] text-steel-500 uppercase">{{ $adjustments->total() }} registros</span></div>
        @if ($adjustments->isEmpty())
            <x-empty-state title="No hay ajustes registrados" description="Las mermas, consumos y correcciones de inventario aparecerán aquí." :action-href="$authenticatedUser?->tienePermiso('MERCADERIA_AJUSTAR') ? route('mercaderia.create') : null" action-label="Registrar primer ajuste"><x-slot:icon><svg class="size-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="m4 7 8-4 8 4-8 4-8-4Z" /><path d="m4 7v10l8 4 8-4V7" /></svg></x-slot:icon></x-empty-state>
        @else
            <div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[1060px] border-collapse text-left" aria-label="Historial de ajustes de mercadería"><thead class="bg-canvas font-mono text-[9px] tracking-[0.16em] text-steel-500 uppercase"><tr><th scope="col" class="px-6 py-3 font-semibold">Ajuste</th><th scope="col" class="px-6 py-3 font-semibold">Producto</th><th scope="col" class="px-6 py-3 font-semibold">Tipo</th><th scope="col" class="px-6 py-3 text-right font-semibold">Aves</th><th scope="col" class="px-6 py-3 text-right font-semibold">Peso</th><th scope="col" class="px-6 py-3 font-semibold">Estado</th><th scope="col" class="px-6 py-3 text-right font-semibold">Acción</th></tr></thead><tbody class="divide-y divide-line">
                @foreach ($adjustments as $adjustment)
                    @php($isEntry = $adjustment->tipoAjuste->naturaleza === 'ENTRADA')
                    <tr class="transition hover:bg-hazard-soft/20"><td class="px-6 py-4"><p class="font-mono text-xs font-semibold text-ink-950">{{ $adjustment->numero_ajuste }}</p><p class="mt-1 text-xs text-steel-500">{{ $adjustment->fecha_ajuste->format('d/m/Y · H:i') }}</p></td><td class="px-6 py-4 font-semibold text-ink-950">{{ $adjustment->producto->nombre }}</td><td class="px-6 py-4"><p class="font-semibold {{ $isEntry ? 'text-signal' : 'text-danger' }}">{{ $adjustment->tipoAjuste->nombre }}</p><p class="mt-1 font-mono text-[8px] tracking-wider text-steel-500 uppercase">{{ $adjustment->tipoAjuste->naturaleza }}</p></td><td class="px-6 py-4 text-right font-mono text-xs font-semibold {{ $adjustment->estaAnulado() ? 'text-steel-500 line-through' : ($isEntry ? 'text-signal' : 'text-danger') }}">{{ $isEntry ? '+' : '−' }} {{ $quantity($adjustment->cantidad_pollos) }}</td><td class="px-6 py-4 text-right font-mono text-xs font-semibold {{ $adjustment->estaAnulado() ? 'text-steel-500 line-through' : ($isEntry ? 'text-signal' : 'text-danger') }}">{{ $isEntry ? '+' : '−' }} {{ $quantity($adjustment->peso_kg, 3) }} kg</td><td class="px-6 py-4"><span class="inline-flex border px-2.5 py-1 font-mono text-[8px] font-semibold tracking-wider uppercase {{ $adjustment->estaAnulado() ? 'border-danger/30 bg-danger-soft text-danger' : 'border-signal/30 bg-signal-soft text-signal' }}">{{ $adjustment->estaAnulado() ? 'Anulado' : 'Vigente' }}</span></td><td class="px-6 py-4 text-right"><a href="{{ route('mercaderia.show', $adjustment) }}" class="inline-flex min-h-9 items-center border border-line px-3 font-mono text-[9px] font-semibold tracking-wider text-ink-700 uppercase transition hover:border-ink-950 hover:bg-ink-950 hover:text-white">Ver detalle</a></td></tr>
                @endforeach
            </tbody></table></div>
            <div class="divide-y divide-line md:hidden">@foreach ($adjustments as $adjustment)@php($isEntry = $adjustment->tipoAjuste->naturaleza === 'ENTRADA')<article class="p-5"><div class="flex items-start justify-between gap-4"><div><p class="font-mono text-xs font-semibold text-ink-950">{{ $adjustment->numero_ajuste }}</p><p class="mt-1 text-xs text-steel-500">{{ $adjustment->fecha_ajuste->format('d/m/Y · H:i') }}</p></div><span class="border px-2 py-1 font-mono text-[8px] font-semibold uppercase {{ $adjustment->estaAnulado() ? 'border-danger/30 bg-danger-soft text-danger' : 'border-signal/30 bg-signal-soft text-signal' }}">{{ $adjustment->estaAnulado() ? 'Anulado' : 'Vigente' }}</span></div><p class="mt-4 font-display text-xl font-bold text-ink-950 uppercase">{{ $adjustment->producto->nombre }}</p><p class="mt-1 text-sm font-semibold {{ $isEntry ? 'text-signal' : 'text-danger' }}">{{ $adjustment->tipoAjuste->nombre }}</p><div class="mt-4 grid grid-cols-2 gap-px border-y border-line bg-line"><div class="bg-paper py-4 pr-3"><p class="font-mono text-[8px] text-steel-500 uppercase">Aves</p><p class="mt-1 font-display text-2xl font-extrabold {{ $isEntry ? 'text-signal' : 'text-danger' }}">{{ $isEntry ? '+' : '−' }} {{ $quantity($adjustment->cantidad_pollos) }}</p></div><div class="bg-paper py-4 pl-3"><p class="font-mono text-[8px] text-steel-500 uppercase">Peso</p><p class="mt-1 font-display text-2xl font-extrabold {{ $isEntry ? 'text-signal' : 'text-danger' }}">{{ $isEntry ? '+' : '−' }} {{ $quantity($adjustment->peso_kg, 3) }}</p></div></div><a href="{{ route('mercaderia.show', $adjustment) }}" class="mt-4 inline-flex min-h-10 w-full items-center justify-center border border-ink-950 font-mono text-[9px] font-semibold tracking-wider text-ink-950 uppercase">Ver detalle</a></article>@endforeach</div>
            <x-catalog-pagination :paginator="$adjustments" />
        @endif
    </section>
@endsection
