@extends('layouts.app')

@section('title', 'Detalle del ajuste')
@section('section', 'Mercadería')

@section('content')
    @php
        $quantity = fn (float|int|string|null $value, int $decimals = 0): string => number_format((float) ($value ?? 0), $decimals, ',', '.');
        $isCancelled = $adjustment->estaAnulado();
        $isEntry = $adjustment->tipoAjuste->naturaleza === 'ENTRADA';
        $userCanCancel = $canCancel && $authenticatedUser?->tienePermiso('MERCADERIA_AJUSTAR');
    @endphp

    <header class="reveal-up flex flex-col gap-6 border-b border-line pb-7 xl:flex-row xl:items-end xl:justify-between">
        <div class="max-w-3xl"><a href="{{ route('mercaderia.index') }}" class="font-mono text-[9px] font-semibold tracking-[0.18em] text-signal uppercase transition hover:text-ink-950">← Volver a mercadería</a><p class="mt-5 font-mono text-[10px] font-semibold tracking-[0.24em] text-signal uppercase">Inventario / {{ $adjustment->numero_ajuste }}</p><h1 class="mt-3 font-display text-4xl leading-none font-extrabold tracking-tight text-ink-950 uppercase sm:text-5xl">Detalle del ajuste</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-steel-500">{{ $adjustment->tipoAjuste->nombre }} registrado sobre {{ $adjustment->producto->nombre }}.</p></div>
        <div class="flex flex-col gap-3 sm:flex-row">@if ($userCanCancel)<a href="{{ route('mercaderia.anulacion.create', $adjustment) }}" class="inline-flex min-h-12 items-center justify-center border border-danger px-5 font-display text-sm font-bold tracking-wider text-danger uppercase transition hover:bg-danger hover:text-white">Anular ajuste</a>@endif<span class="inline-flex min-h-12 items-center justify-center border px-5 font-mono text-[10px] font-semibold tracking-wider uppercase {{ $isCancelled ? 'border-danger/30 bg-danger-soft text-danger' : 'border-signal/30 bg-signal-soft text-signal' }}">{{ $isCancelled ? 'Ajuste anulado' : 'Ajuste vigente' }}</span></div>
    </header>

    <section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Resumen del ajuste">
        <div class="border-l-4 {{ $isEntry ? 'border-signal' : 'border-danger' }} bg-paper p-5 shadow-sm"><p class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Naturaleza</p><p class="mt-2 font-display text-3xl font-extrabold {{ $isEntry ? 'text-signal' : 'text-danger' }}">{{ $isEntry ? 'Entrada' : 'Salida' }}</p></div>
        <div class="border-l-4 border-hazard bg-paper p-5 shadow-sm"><p class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Cantidad</p><p class="mt-2 font-display text-3xl font-extrabold {{ $isCancelled ? 'text-steel-500 line-through' : 'text-ink-950' }}">{{ $isEntry ? '+' : '−' }} {{ $quantity($adjustment->cantidad_pollos) }} aves</p></div>
        <div class="border-l-4 border-hazard bg-paper p-5 shadow-sm"><p class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Peso</p><p class="mt-2 font-display text-3xl font-extrabold {{ $isCancelled ? 'text-steel-500 line-through' : 'text-ink-950' }}">{{ $isEntry ? '+' : '−' }} {{ $quantity($adjustment->peso_kg, 3) }} kg</p></div>
        <div class="industrial-hatch border-l-4 border-hazard bg-ink-950 p-5 text-white shadow-sm"><p class="font-mono text-[8px] tracking-wider text-hazard uppercase">Saldo actual del producto</p><p class="mt-2 font-display text-2xl font-extrabold">{{ $quantity($balance->pollos_disponibles) }} aves</p><p class="mt-1 text-xs text-steel-300">{{ $quantity($balance->kg_disponibles, 3) }} kg disponibles</p></div>
    </section>

    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_380px]">
        <section class="reveal-up reveal-up-delay-1 border border-line bg-paper shadow-panel" aria-labelledby="adjustment-data-title"><div class="border-b border-line px-5 py-5 sm:px-6"><p class="font-mono text-[9px] font-semibold tracking-[0.18em] text-signal uppercase">Documento / Auditoría</p><h2 id="adjustment-data-title" class="mt-1 font-display text-2xl font-bold text-ink-950 uppercase">Datos del movimiento</h2></div><dl class="grid sm:grid-cols-2"><div class="border-b border-line p-5 sm:border-r sm:p-6"><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Número</dt><dd class="mt-2 font-mono text-sm font-semibold text-ink-950">{{ $adjustment->numero_ajuste }}</dd></div><div class="border-b border-line p-5 sm:p-6"><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Fecha y hora</dt><dd class="mt-2 font-semibold text-ink-950">{{ $adjustment->fecha_ajuste->format('d/m/Y · H:i:s') }}</dd></div><div class="border-b border-line p-5 sm:border-r sm:p-6"><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Producto</dt><dd class="mt-2 font-display text-xl font-bold text-ink-950 uppercase">{{ $adjustment->producto->nombre }}</dd><dd class="mt-1 text-xs text-steel-500">{{ $adjustment->producto->descripcion ?: 'Sin descripción adicional' }}</dd></div><div class="border-b border-line p-5 sm:p-6"><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Tipo</dt><dd class="mt-2 font-semibold text-ink-950">{{ $adjustment->tipoAjuste->nombre }}</dd><dd class="mt-1 font-mono text-[9px] text-steel-500 uppercase">{{ $adjustment->tipoAjuste->codigo }}</dd></div><div class="border-b border-line p-5 sm:col-span-2 sm:p-6"><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Motivo</dt><dd class="mt-2 text-sm leading-6 text-ink-700">{{ $adjustment->motivo }}</dd></div><div class="p-5 sm:col-span-2 sm:p-6"><dt class="font-mono text-[8px] tracking-wider text-steel-500 uppercase">Registrado por</dt><dd class="mt-2 font-semibold text-ink-950">{{ $adjustment->usuario->nombreCompleto() }}</dd><dd class="mt-1 text-xs text-steel-500">{{ $adjustment->usuario->usuario }}</dd></div></dl></section>

        <aside class="grid content-start gap-6">
            <section class="reveal-up reveal-up-delay-2 border border-line bg-paper p-5 shadow-panel"><p class="font-mono text-[9px] font-semibold tracking-wider text-signal uppercase">Producto / Existencia</p><h2 class="mt-2 font-display text-2xl font-bold text-ink-950 uppercase">{{ $adjustment->producto->nombre }}</h2><div class="mt-5 grid grid-cols-2 gap-3"><div class="border border-line bg-canvas p-4"><p class="font-mono text-[8px] text-steel-500 uppercase">Aves</p><p class="mt-2 font-display text-2xl font-extrabold text-ink-950">{{ $quantity($balance->pollos_disponibles) }}</p></div><div class="border border-line bg-canvas p-4"><p class="font-mono text-[8px] text-steel-500 uppercase">Peso</p><p class="mt-2 font-display text-2xl font-extrabold text-ink-950">{{ $quantity($balance->kg_disponibles, 3) }}</p><p class="text-xs text-steel-500">kg</p></div></div>@if ($authenticatedUser?->tienePermiso('MERCADERIA_AJUSTAR'))<a href="{{ route('mercaderia.create', ['producto' => $adjustment->producto_id]) }}" class="mt-4 inline-flex min-h-11 w-full items-center justify-center border border-ink-950 font-display text-xs font-bold tracking-wider text-ink-950 uppercase transition hover:bg-ink-950 hover:text-white">Registrar otro ajuste</a>@endif</section>

            @if ($isCancelled)
                <section class="reveal-up reveal-up-delay-2 border-l-4 border-danger bg-danger-soft p-5" aria-labelledby="adjustment-cancellation-title"><p class="font-mono text-[9px] font-semibold tracking-wider text-danger uppercase">Anulación registrada</p><h2 id="adjustment-cancellation-title" class="mt-2 font-display text-xl font-bold text-ink-950 uppercase">{{ $adjustment->anulado_at->format('d/m/Y · H:i:s') }}</h2><p class="mt-2 text-sm text-ink-700">Por {{ $adjustment->anuladoPor?->nombreCompleto() ?? 'Usuario no disponible' }}.</p><p class="mt-4 border-t border-danger/20 pt-4 text-sm leading-6 text-ink-700">{{ $adjustment->motivo_anulacion }}</p></section>
            @elseif ($cancellationBlockReason)
                <section class="reveal-up reveal-up-delay-2 border-l-4 border-hazard bg-hazard-soft p-5"><p class="font-mono text-[9px] font-semibold tracking-wider text-ink-950 uppercase">Anulación bloqueada</p><p class="mt-2 text-sm leading-6 text-ink-700">{{ $cancellationBlockReason }}</p></section>
            @else
                <section class="reveal-up reveal-up-delay-2 border-l-4 border-signal bg-signal-soft p-5"><p class="font-mono text-[9px] font-semibold tracking-wider text-signal uppercase">Movimiento reversible</p><p class="mt-2 text-sm leading-6 text-ink-700">Este ajuste puede anularse mientras no esté conciliado ni provoque un saldo negativo.</p></section>
            @endif
        </aside>
    </div>
@endsection
